#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive Quiz Bank for Level A2 (Goethe A2 Exam Standard):
15 Lessons, 10 in-depth questions per lesson = 150 total questions.
Covers Präteritum, Wechselpräpositionen, Adjective Declensions (Typ I, II, III),
Comparative/Superlative, Subordinate clauses (dass, weil, wenn), Reflexive verbs,
Passive voice (Vorgangspassiv Präsens), Relative clauses (Nom./Akk.),
Konjunktiv II (höfliche Bitte/Wunsch), Double object word order, and Goethe A2 exam training.
"""

A2_QUIZZES = {
    "A2_L01": [
        {"id": "A2_L01_Q1", "type": "GRAMMAR_FILL", "question": "请选用助动词 sein 的过去时 (Präteritum) 填空：'Letztes Jahr _____ ich in Wien.'", "options": ["bin", "war", "warst", "waren"], "correctIndex": 1, "explanation": "主语为第一人称单数 ich，sein 的过去时形式为 war。在描述过去经历或简历时，sein 普遍优先使用过去时。"},
        {"id": "A2_L01_Q2", "type": "GRAMMAR_FILL", "question": "助动词 haben 的第三人称单数过去时形式是：'Mit 20 Jahren _____ er noch kein Auto.'", "options": ["hat", "hatte", "hattest", "hatten"], "correctIndex": 1, "explanation": "er 的 haben 过去时变位是 hatte（第一与第三人称单数同形：ich hatte, er/sie/es hatte）。"},
        {"id": "A2_L01_Q3", "type": "GRAMMAR_FILL", "question": "时间连词选择（过去单次发生的事件）：'_____ ich 6 Jahre alt war, zogen wir nach München.'", "options": ["Wenn", "Als", "Wann", "Weil"], "correctIndex": 1, "explanation": "als 用于引导过去单次发生的时间段或时间点从句；wenn 则用于现在/将来的时间或过去多次重复发生的事件。"},
        {"id": "A2_L01_Q4", "type": "GRAMMAR_FILL", "question": "时间连词选择（过去多次重复）：'Immer _____ mein Großvater mich besuchte, brachte er Schokolade mit.'", "options": ["als", "wenn", "wann", "während"], "correctIndex": 1, "explanation": "句中有 Immer 明确表示过去多次重复发生的习惯性动作，引导词必须用 wenn (immer wenn)。"},
        {"id": "A2_L01_Q5", "type": "VOCAB_MEANING", "question": "求职简历必备词：'der Lebenslauf' 的准确含义是：", "options": ["求职信", "个人简历 / 履历", "劳动合同", "学历公证书"], "correctIndex": 1, "explanation": "der Lebenslauf 指履历、个人简历（curriculum vitae），在求职申请 (Bewerbung) 中不可或缺。"},
        {"id": "A2_L01_Q6", "type": "GRAMMAR_FILL", "question": "规则动词 machen 的过去时 (ich/er) 形式是：", "options": ["machte", "machten", "gemacht", "mache"], "correctIndex": 0, "explanation": "规则弱变化动词的过去时词干后加 -te：ich machte, er machte。"},
        {"id": "A2_L01_Q7", "type": "GRAMMAR_FILL", "question": "强变化动词 kommen 的过去时形式是：'Gestern _____ mein Onkel überraschend zu Besuch.'", "options": ["kommst", "kam", "gekommen", "kamt"], "correctIndex": 1, "explanation": "kommen 是强变化动词，现在时 kommen - 过去时 kam - 过去分词 gekommen。第三人称单数过去时无词尾，为 kam。"},
        {"id": "A2_L01_Q8", "type": "SENTENCE_BUILDER", "question": "将下列时间状语与过去时按正确语序排列：[vor zwei Jahren / er / das Studium / abschließen (过去时 schloss ab)]", "options": ["Vor zwei Jahren er schloss das Studium ab.", "Vor zwei Jahren schloss er das Studium ab.", "Schloss er vor zwei Jahren das Studium ab.", "Vor zwei Jahren er das Studium abschloss."], "correctIndex": 1, "explanation": "时间状语 Vor zwei Jahren 占第一位，变位动词 schloss 占第二位，主语 er 居第三位，可分前缀 ab 置于句末构成框架结构。"},
        {"id": "A2_L01_Q9", "type": "ARTICLE", "question": "名词 'Erfahrung' (经验、经历) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "词尾为 -ung 的名词全部为阴性名词：die Erfahrung (Pl. die Erfahrungen)。"},
        {"id": "A2_L01_Q10", "type": "EXAM_REAL", "question": "简历中关于语言水平的描述：'Deutsch in Wort und Schrift' 意思是：", "options": ["德语仅会听说", "德语仅会读写", "德语听说读写熟练精通", "德语入门刚起步"], "correctIndex": 2, "explanation": "'in Wort und Schrift' 是德语职场简历固定成语，意为“口头与书面皆熟练”（听说读写皆通）。"}
    ],
    "A2_L02": [
        {"id": "A2_L02_Q1", "type": "GRAMMAR_FILL", "question": "情态动词 müssen 的过去时变位：'Gestern war ich krank und _____ zu Hause bleiben.'", "options": ["muss", "musste", "müsste", "mussten"], "correctIndex": 1, "explanation": "müssen 的过去时词干不带变音符号 umlaut，变位为 ich musste, er musste。"},
        {"id": "A2_L02_Q2", "type": "GRAMMAR_FILL", "question": "情态动词 dürfen 的过去时第三人称单数是：'Als Kind _____ er nicht spät fernsehen.'", "options": ["darf", "durfte", "dürfte", "durften"], "correctIndex": 1, "explanation": "dürfen 的过去时同样去变音，形式为 durfte (ich durfte, er durfte)。注意 dürfte 是第二虚拟式（表示推测）。"},
        {"id": "A2_L02_Q3", "type": "GRAMMAR_FILL", "question": "情态动词 können 的过去时：'Mit 5 Jahren _____ sie schon schwimmen.'", "options": ["kann", "konnte", "könnte", "konnten"], "correctIndex": 1, "explanation": "können 过去时无变音，单数第三人称为 konnte。"},
        {"id": "A2_L02_Q4", "type": "GRAMMAR_FILL", "question": "情态动词 wollen 的过去时第一人称复数：'Wir _____ eigentlich ins Kino gehen, aber hatten keine Zeit.'", "options": ["wollen", "wollten", "wollt", "gewollt"], "correctIndex": 1, "explanation": "wollen 的过去时词干为 wollt-，第一人称复数加 -en，即 wir wollten。"},
        {"id": "A2_L02_Q5", "type": "VOCAB_MEANING", "question": "德国特色教育制度：'das duale System' 核心特点是：", "options": ["纯大学理论研究", "企业实践操作与职业学校理论教学双元结合", "全日制线上自学", "只在技工学校实训不拿工资"], "correctIndex": 1, "explanation": "德国双元制职业教育（Duales Ausbildungssystem）是德国制造的支柱，学生在企业带薪实习并在职校系统学习理论。"},
        {"id": "A2_L02_Q6", "type": "VOCAB_MEANING", "question": "单词 'die Ausbildung' 的中文意思是：", "options": ["中小学基础教育", "职业培训 / 职业教育", "大学博士深造", "出国交换项目"], "correctIndex": 1, "explanation": "die Ausbildung 特指职业技能培训或学徒培训（Ausbildung zum Mechatroniker 等）。"},
        {"id": "A2_L02_Q7", "type": "ARTICLE", "question": "名词 'Zeugnis' (成绩单、证明书) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "以 -nis 结尾的名词绝大多数为中性：das Zeugnis (Pl. die Zeugnisse)。"},
        {"id": "A2_L02_Q8", "type": "GRAMMAR_FILL", "question": "情态动词 sollen 的过去时：'Der Arzt sagte, ich _____ viel Wasser trinken.'", "options": ["soll", "sollte", "solltest", "gesollt"], "correctIndex": 1, "explanation": "sollen 过去时为 sollte。常用于转述医嘱或他人转达的要求：Der Arzt sagte, ich sollte ...。"},
        {"id": "A2_L02_Q9", "type": "EXAM_REAL", "question": "歌德 A2 听力/阅读：'Ich habe die Prüfung bestanden!' 意思与最佳回应是：", "options": ["我考试挂科了 / Tut mir leid!", "我通过了考试！ / Herzlichen Glückwunsch!", "我放弃了考试 / Schade!", "我在准备考试 / Auf Wiedersehen!"], "correctIndex": 1, "explanation": "die Prüfung bestehen 意为“通过考试”，完成时为 bestanden haben，听到喜讯应热烈祝贺：Herzlichen Glückwunsch!"},
        {"id": "A2_L02_Q10", "type": "SENTENCE_BUILDER", "question": "将含有情态动词过去时的句子正确语序选出：", "options": ["Gestern ich musste lange im Büro bleiben.", "Gestern musste ich lange im Büro bleiben.", "Gestern musste lange ich im Büro bleiben.", "Gestern im Büro ich musste lange bleiben."], "correctIndex": 1, "explanation": "状语 Gestern 占第 1 位，情态动词过去时 musste 占第 2 位，主语 ich 紧随其后，动词原形 bleiben 置于句末构成框架。"}
    ],
    "A2_L03": [
        {"id": "A2_L03_Q1", "type": "GRAMMAR_FILL", "question": "静止地点（静三：Wo?）选介词冠词：'Das Buch liegt auf _____ Tisch.' (阳性 der Tisch)", "options": ["den", "dem", "das", "des"], "correctIndex": 1, "explanation": "liegen 表示静止状态，回答 Wo?，静止用第三格 (Dativ)；阳性 der Tisch 变为 dem Tisch。"},
        {"id": "A2_L03_Q2", "type": "GRAMMAR_FILL", "question": "动态方向（动四：Wohin?）选介词冠词：'Ich lege das Buch auf _____ Tisch.' (阳性 der Tisch)", "options": ["den", "dem", "das", "des"], "correctIndex": 0, "explanation": "legen 表示把某物平放过去的动作，回答 Wohin?，动态用第四格 (Akkusativ)；阳性 der Tisch 变为 den Tisch。"},
        {"id": "A2_L03_Q3", "type": "GRAMMAR_FILL", "question": "动词成对辨析（立着放 vs 站立）：'Er _____ die Flasche auf den Tisch; jetzt _____ sie dort.'", "options": ["stellt / steht", "steht / stellt", "liegt / legt", "sitzt / setzt"], "correctIndex": 0, "explanation": "stellen（及物，立着放，支配 Akk）与 stehen（不及物，立着，支配 Dat）。句一有宾语 Flasche 且到 auf den Tisch，用 stellt；句二为静止状态，用 steht。"},
        {"id": "A2_L03_Q4", "type": "GRAMMAR_FILL", "question": "介词缩合（an + dem）：'Das Bild hängt _____ Wand.' (阴性 die Wand, 静止 Wo?)", "options": ["an der", "an die", "am", "ans"], "correctIndex": 0, "explanation": "Wand 是阴性名词 die Wand，第三格为 an der Wand。如果是阳性或中性才会缩合为 am (an dem)。"},
        {"id": "A2_L03_Q5", "type": "GRAMMAR_FILL", "question": "九大静动两便介词 (Wechselpräpositionen) 不包括以下哪一个？", "options": ["neben", "zwischen", "durch", "hinter"], "correctIndex": 2, "explanation": "九大九变介词是：an, auf, hinter, in, neben, über, unter, vor, zwischen。而 durch 永远只支配第四格 (Akkusativ)。"},
        {"id": "A2_L03_Q6", "type": "VOCAB_MEANING", "question": "职场高频词：'die Besprechung' 的意思是：", "options": ["请假单", "工作会议 / 业务会谈", "辞职信", "年终奖金"], "correctIndex": 1, "explanation": "die Besprechung (或 das Meeting) 指工作会议、洽谈商讨。例如：Wir haben um 10 Uhr eine Besprechung."},
        {"id": "A2_L03_Q7", "type": "ARTICLE", "question": "名词 'Kollege' (男同事) 与 'Kollegin' (女同事) 的定冠词分别是：", "options": ["der / die", "die / der", "das / die", "der / das"], "correctIndex": 0, "explanation": "Kollege 为弱变化阳性名词 (der Kollege)，Kollegin 为阴性名词 (die Kollegin)。"},
        {"id": "A2_L03_Q8", "type": "SENTENCE_BUILDER", "question": "商务电子邮件经典称谓（收件人为 Herr Müller 时）：", "options": ["Lieber Herr Müller,", "Sehr geehrter Herr Müller,", "Guten Morgen Müller,", "Hallo Herr Müller!"], "correctIndex": 1, "explanation": "正式商务邮件收信人为男性时，最标准尊称是：'Sehr geehrter Herr Müller,'（女性用 Sehr geehrte Frau ...）。注意逗号后首字母小写。"},
        {"id": "A2_L03_Q9", "type": "GRAMMAR_FILL", "question": "动态方向填空：'Die Katze läuft unter _____ Sofa.' (中性 das Sofa)", "options": ["das", "dem", "den", "der"], "correctIndex": 0, "explanation": "动作是跑到沙发下（回答 Wohin?），中性名词在第四格中定冠词仍为 das。"},
        {"id": "A2_L03_Q10", "type": "EXAM_REAL", "question": "德语邮件标准结尾客套语是：", "options": ["Bis morgen", "Mit freundlichen Grüßen", "Tschüss", "Schöne Grüße an alle"], "correctIndex": 1, "explanation": "正式书信与商务电邮的标准落款公式语是 'Mit freundlichen Grüßen'（致以亲切的问候）。"}
    ],
    "A2_L04": [
        {"id": "A2_L04_Q1", "type": "GRAMMAR_FILL", "question": "定冠词后第一格形容词词尾（Typ I）：'Der _____ Wagen gehört mir.' (neu)", "options": ["neue", "neuer", "neuen", "neuem"], "correctIndex": 0, "explanation": "定冠词后（Typ I 形容词弱变化），第一格阳、阴、中性单数形容词词尾一律加 -e：der neue Wagen, die neue Wohnung, das neue Haus。"},
        {"id": "A2_L04_Q2", "type": "GRAMMAR_FILL", "question": "定冠词后第四格阳性形容词词尾：'Ich kaufe den _____ Schrank.' (groß)", "options": ["große", "großer", "großen", "großes"], "correctIndex": 2, "explanation": "定冠词后第四格阳性冠词为 den，其后的形容词词尾必加 -en：den großen Schrank。"},
        {"id": "A2_L04_Q3", "type": "GRAMMAR_FILL", "question": "定冠词后第三格形容词词尾铁律：'In der _____ Wohnung gibt es viel Licht.' (hell)", "options": ["helle", "hellen", "heller", "hellem"], "correctIndex": 1, "explanation": "定冠词后（Typ I）在所有第三格、第二格以及所有复数情况下，形容词词尾无条件全部加 -en！故为 in der hellen Wohnung。"},
        {"id": "A2_L04_Q4", "type": "GRAMMAR_FILL", "question": "定冠词后复数形容词词尾：'Die _____ Fenster sind sauber.' (groß)", "options": ["große", "großer", "großen", "großes"], "correctIndex": 2, "explanation": "在定冠词 die 后的复数名词，形容词词尾统一必须加 -en：die großen Fenster。"},
        {"id": "A2_L04_Q5", "type": "VOCAB_MEANING", "question": "租房广告核心术语：'die Warmmiete' 包含什么？", "options": ["仅房屋净租金（不含任何杂费）", "冷租金加上暖气、水、垃圾等附加杂费的总租金", "中介费与押金总和", "仅指冬季取暖补贴"], "correctIndex": 1, "explanation": "Kaltmiete（冷租）是不含物业与能耗的纯房租；Warmmiete（暖租）已包含暖气、水及公摊物业杂费 (Nebenkosten)。"},
        {"id": "A2_L04_Q6", "type": "ARTICLE", "question": "名词 'Möbel' (家具) 在德语中常用的用法特征是：", "options": ["单数阳性 der Möbel", "中性单数 das Möbel，通常多用复数 die Möbel", "阴性单数 die Möbel", "永远不能用于复数"], "correctIndex": 1, "explanation": "das Möbel 单数指一件家具，日常中最常以复数 die Möbel 出现泛指全部家具。"},
        {"id": "A2_L04_Q7", "type": "GRAMMAR_FILL", "question": "定冠词后第四格中性名词的形容词词尾：'Wir renovieren das _____ Zimmer.' (alt)", "options": ["alte", "altes", "alten", "alter"], "correctIndex": 0, "explanation": "中性名词第四格定冠词为 das，Typ I 弱变化词尾仍保持 -e：das alte Zimmer。"},
        {"id": "A2_L04_Q8", "type": "VOCAB_MEANING", "question": "租房合同中的 'die Kaution' 指的是：", "options": ["房屋中介佣金", "租房押金（通常为2至3个月冷租）", "钥匙费", "垃圾处理税"], "correctIndex": 1, "explanation": "die Kaution 是承租人在入住前向房东支付的租房押金（Mietkaution），退租时若房屋无损则全额退还。"},
        {"id": "A2_L04_Q9", "type": "SENTENCE_BUILDER", "question": "形容词词尾判断：'Der nette Herr hilft der _____ Nachbarin.' (alt)", "options": ["alte", "alten", "alter", "altem"], "correctIndex": 1, "explanation": "helfen 支配第三格，der Nachbarin 是第三格阴性，定冠词后第三格形容词词尾必须加 -en：der alten Nachbarin。"},
        {"id": "A2_L04_Q10", "type": "EXAM_REAL", "question": "在德国搬新家后，法律强制要求在一两周内到市政厅办理的手续是：", "options": ["das Visum verlängern", "sich beim Einwohnermeldeamt anmelden", "den Führerschein abgeben", "einen Hund kaufen"], "correctIndex": 1, "explanation": "在德国更换住址后必须于规定期限内到市政居民户籍处 (Einwohnermeldeamt / Bürgeramt) 办理户籍登记 (Anmeldung)。"}
    ],
    "A2_L05": [
        {"id": "A2_L05_Q1", "type": "GRAMMAR_FILL", "question": "不定冠词后第一格阳性形容词词尾（Typ II）：'Hier steht ein _____ Tisch.' (schön)", "options": ["schöne", "schöner", "schönes", "schönen"], "correctIndex": 1, "explanation": "不定冠词 ein 无特征性阳性标记词尾，因此后面的形容词必须体现性属标记 -er：ein schöner Tisch。"},
        {"id": "A2_L05_Q2", "type": "GRAMMAR_FILL", "question": "不定冠词后第一格中性形容词词尾：'Das ist ein _____ Bild.' (neu)", "options": ["neue", "neuer", "neues", "neuen"], "correctIndex": 2, "explanation": "不定冠词 ein 同样不体现中性标记，故形容词必须体现中性 -es：ein neues Bild (das Bild)。"},
        {"id": "A2_L05_Q3", "type": "GRAMMAR_FILL", "question": "不定冠词后第四格阳性形容词词尾：'Ich habe einen _____ Fernseher gekauft.' (teuer)", "options": ["teuren", "teure", "teures", "teurer"], "correctIndex": 0, "explanation": "第四格阳性不定冠词为 einen，形容词词尾一律加 -en：einen teuren Fernseher（注意 teuer 加词尾时中间 -e- 弱化脱落为 teur-）。"},
        {"id": "A2_L05_Q4", "type": "GRAMMAR_FILL", "question": "否定冠词 kein 后第一格复数形容词词尾：'Hier gibt es keine _____ Plätze.' (frei)", "options": ["freie", "freien", "freier", "freies"], "correctIndex": 1, "explanation": "在否定冠词 kein- 或物主代词 mein- 后的复数名词，形容词词尾一律加 -en：keine freien Plätze。"},
        {"id": "A2_L05_Q5", "type": "VOCAB_MEANING", "question": "网购退换货术语：'die Rücksendung / der Umtausch' 含义分别是：", "options": ["发货追踪 / 付款", "退货寄回 / 换货", "取消订单 / 促销打折", "包裹丢失 / 索赔"], "correctIndex": 1, "explanation": "die Rücksendung 意为退货邮寄，der Umtausch 意为调换货品。"},
        {"id": "A2_L05_Q6", "type": "GRAMMAR_FILL", "question": "物主代词后第三格中性形容词词尾：'In meinem _____ Zimmer steht ein Schrank.' (klein)", "options": ["kleines", "kleinen", "kleine", "kleiner"], "correctIndex": 1, "explanation": "在所有第三格位置，无论 Typ I 还是 Typ II，形容词词尾统统加 -en：in meinem kleinen Zimmer。"},
        {"id": "A2_L05_Q7", "type": "ARTICLE", "question": "名词 'Garantie' (保修期、质保) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "以 -ie 结尾的外来名词多为阴性：die Garantie (Pl. die Garantien)。"},
        {"id": "A2_L05_Q8", "type": "VOCAB_MEANING", "question": "投诉信必备表达：'Die Ware ist beschädigt angekommen.' 意思是：", "options": ["商品尚未发出", "商品送达时已经损坏", "商品价格太高", "商品是假冒伪劣"], "correctIndex": 1, "explanation": "beschädigt 意为受损的、损坏的，常用于商品运输破损的售后投诉维权。"},
        {"id": "A2_L05_Q9", "type": "GRAMMAR_FILL", "question": "不定冠词后阴性第一格形容词词尾：'Sie ist eine _____ Kollegin.' (freundlich)", "options": ["freundliche", "freundlicher", "freundlichen", "freundliches"], "correctIndex": 0, "explanation": "阴性第一格不定冠词为 eine，形容词加 -e：eine freundliche Kollegin。"},
        {"id": "A2_L05_Q10", "type": "EXAM_REAL", "question": "歌德 A2 写作（商品投诉与要求退款）：'Ich möchte mein Geld _____.'", "options": ["wegwerfen", "zurückbekommen", "bezahlen", "schenken"], "correctIndex": 1, "explanation": "zurückbekommen 意为“拿回、取回”，Ich möchte mein Geld zurückbekommen 是要求商家退款的标准地道句式。"}
    ],
    "A2_L06": [
        {"id": "A2_L06_Q1", "type": "GRAMMAR_FILL", "question": "形容词比较级规则构成：'Ein Zug fährt schnell, aber ein Flugzeug fliegt noch _____.'", "options": ["schneller", "am schnellsten", "schnellste", "schneller als"], "correctIndex": 0, "explanation": "形容词比较级基础词尾为 -er：schnell -> schneller。"},
        {"id": "A2_L06_Q2", "type": "GRAMMAR_FILL", "question": "比较级不规则变音：'Mein Bruder ist 18 Jahre alt, aber ich bin _____.' (alt)", "options": ["alter", "älter", "am ältesten", "ältere"], "correctIndex": 1, "explanation": "多数单音节 a, o, u 元音形容词在变比较级时发生变音 umlaut：alt -> älter, groß -> größer, jung -> jünger。"},
        {"id": "A2_L06_Q3", "type": "GRAMMAR_FILL", "question": "形容词 gut 的不规则比较级与最高级是：", "options": ["guter / am gutesten", "besser / am besten", "lieber / am liebsten", "mehr / am meisten"], "correctIndex": 1, "explanation": "gut 的比较级是 besser，最高级是 am besten。"},
        {"id": "A2_L06_Q4", "type": "GRAMMAR_FILL", "question": "比较连接词选择（同级相等比较 vs 不等比较）：'Er ist genauso groß _____ ich, aber er läuft schneller _____ ich.'", "options": ["als / wie", "wie / als", "wie / wie", "als / als"], "correctIndex": 1, "explanation": "同级相等比较（so / genauso ...）用 wie；不等比较（比较级 ...）强制用 als！"},
        {"id": "A2_L06_Q5", "type": "GRAMMAR_FILL", "question": "副词 gern 的比较级与最高级：'Ich trinke Tee, aber ich trinke _____ Kaffee.'", "options": ["gerner", "lieber", "besser", "mehr"], "correctIndex": 1, "explanation": "gern 表示喜好，比较级是不规则的 lieber（更喜欢），最高级是 am liebsten。"},
        {"id": "A2_L06_Q6", "type": "GRAMMAR_FILL", "question": "形容词 viel 的比较级与最高级是：", "options": ["vieler / am vielsten", "mehr / am meisten", "besser / am besten", "größer / am größten"], "correctIndex": 1, "explanation": "viel 的比较级为 mehr，最高级为 am meisten。"},
        {"id": "A2_L06_Q7", "type": "VOCAB_MEANING", "question": "德国铁路 (DB) 广播必备：'Der ICE hat heute 20 Minuten Verspätung.' 意思是：", "options": ["列车提前20分钟抵达", "列车晚点延误20分钟", "列车在20号站台发车", "列车中途停靠20分钟"], "correctIndex": 1, "explanation": "die Verspätung 意为晚点、延误；Verspätung haben 是德铁播报最常见的句型。"},
        {"id": "A2_L06_Q8", "type": "ARTICLE", "question": "名词 'Gleis' (铁轨、站台) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "Gleis 是中性名词：das Gleis (Pl. die Gleise)，如 Auf Gleis 4 fährt ein...。"},
        {"id": "A2_L06_Q9", "type": "GRAMMAR_FILL", "question": "最高级作定语时的词尾：'Das ist das _____ Gebäude der Stadt.' (hoch)", "options": ["höchste", "am höchsten", "höher", "hohe"], "correctIndex": 0, "explanation": "hoch 的最高级词干变为 höchst-，作定语修饰中性名词 das Gebäude 时加定冠词词尾 -e：das höchste Gebäude。"},
        {"id": "A2_L06_Q10", "type": "EXAM_REAL", "question": "歌德 A2 车站问路：'Muss ich umsteigen?' 的含义是：", "options": ["我需要检票吗？", "我需要中途换乘转车吗？", "我可以退票吗？", "什么时候发车？"], "correctIndex": 1, "explanation": "umsteigen 意为换乘、转车（einsteigen 上车，aussteigen 下车）。"}
    ],
    "A2_L07": [
        {"id": "A2_L07_Q1", "type": "GRAMMAR_FILL", "question": "连词 dass 引导的宾语从句语序铁律：'Ich weiß, dass er morgen nach Berlin _____.'", "options": ["fährt", "fahren", "wird fahren", "ist gefahren"], "correctIndex": 0, "explanation": "从属连词 dass 引导从句，变位动词必须置于从句末尾 (Verb am Ende)！故 fährt 在句尾。"},
        {"id": "A2_L07_Q2", "type": "GRAMMAR_FILL", "question": "原因从句连词 weil 语序填空：'Ich lerne Deutsch, weil ich in Deutschland studieren _____.'", "options": ["will", "wollen", "habe", "werde"], "correctIndex": 0, "explanation": "weil 引导原因从句，情态动词变位 will 置于从句的最后一位（在不定式 studieren 之后）。"},
        {"id": "A2_L07_Q3", "type": "GRAMMAR_FILL", "question": "条件连词 wenn 引导主从句语序：'Wenn das Wetter schön ist, _____ wir einen Ausflug.'", "options": ["machen", "wir machen", "machen wir", "gemacht"], "correctIndex": 2, "explanation": "当从句居前时，整个从句相当于主句的第 1 位成分，主句紧随其后必须是动词占第 2 位：machen wir ...！"},
        {"id": "A2_L07_Q4", "type": "VOCAB_MEANING", "question": "酒店预订术语：'ein Einzelzimmer mit Halbpension' 包含什么？", "options": ["双人间含全日三餐", "单人间含早餐和一顿正餐（半膳宿）", "套房仅含早餐", "多人间不含任何餐食"], "correctIndex": 1, "explanation": "Einzelzimmer 为单人间；Halbpension（半膳）指除住宿和早餐外还包含一顿正餐（通常是晚餐）；Vollpension 则是全膳（一日三餐）。"},
        {"id": "A2_L07_Q5", "type": "ARTICLE", "question": "名词 'Koffer' (行李箱) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "Koffer 是阳性名词：der Koffer (Pl. die Koffer)。"},
        {"id": "A2_L07_Q6", "type": "GRAMMAR_FILL", "question": "间接疑问句连词 ob（是否）：'Können Sie mir sagen, _____ der Zug pünktlich ankommt?'", "options": ["dass", "ob", "weil", "wenn"], "correctIndex": 1, "explanation": "由 Ja/Nein 是非疑问句转化来的间接宾语从句，连接词必须用 ob（是否），动词 ankommt 置于从句末尾。"},
        {"id": "A2_L07_Q7", "type": "SENTENCE_BUILDER", "question": "判断下列带 dass 从句的正误与语序：", "options": ["Sie hat gesagt, dass sie kommt heute nicht.", "Sie hat gesagt, dass sie heute nicht kommt.", "Sie hat gesagt, dass heute nicht sie kommt.", "Sie hat gesagt, dass nicht kommt sie heute."], "correctIndex": 1, "explanation": "dass 引导从句，变位动词 kommt 必须放在从句的绝对末位：... dass sie heute nicht kommt。"},
        {"id": "A2_L07_Q8", "type": "VOCAB_MEANING", "question": "机场海关术语：'das Handgepäck' 的含义是：", "options": ["托运行李", "随身手提行李", "超重行李罚款", "行李寄存牌"], "correctIndex": 1, "explanation": "das Handgepäck 指旅客随身携带登机的轻便手提行李；Aufgabegepäck 为托运行李。"},
        {"id": "A2_L07_Q9", "type": "GRAMMAR_FILL", "question": "连词 ob vs dass 辨析：'Ich bin nicht sicher, _____ das Hotel noch freie Zimmer hat.'", "options": ["dass", "ob", "weil", "wenn"], "correctIndex": 1, "explanation": "主句是不确定状态 (nicht sicher sein)，表示未知的是非疑问，从句需用 ob（是否）。"},
        {"id": "A2_L07_Q10", "type": "EXAM_REAL", "question": "歌德 A2 口语旅行场景：在前台退房退房卡时的地道表达是：", "options": ["Ich möchte auschecken.", "Ich möchte einchecken.", "Ich will schlafen.", "Geben Sie mir ein Zimmer."], "correctIndex": 0, "explanation": "auschecken 意为办理退房结算离开；einchecken 是办理入住登记。"}
    ],
    "A2_L08": [
        {"id": "A2_L08_Q1", "type": "GRAMMAR_FILL", "question": "对第二人称单数 du 的命令式构成：'_____ nicht so schnell!' (fahren)", "options": ["Fährst", "Fahr", "Fahre nicht", "Fährt"], "correctIndex": 1, "explanation": "对 du 的命令式去词尾 -st 和人称代词 du；且强变化动词原本变音 a->ä 的变音必须去掉，故 fahren 的命令式为 Fahr! (而非 *Fähr!)。"},
        {"id": "A2_L08_Q2", "type": "GRAMMAR_FILL", "question": "对 du 的强变化换音动词命令式：'_____ die Medizin!' (nehmen)", "options": ["Nehm", "Nimm", "Nehme", "Nehmt"], "correctIndex": 1, "explanation": "词干元音 e 变为 i 或 ie 的强变化动词，命令式必须保留换音：nehmen -> Nimm!，geben -> Gib!，lesen -> Lies!"},
        {"id": "A2_L08_Q3", "type": "GRAMMAR_FILL", "question": "对第二人称复数 ihr 的命令式构成：'Kinder, _____ bitte die Hausaufgaben!' (machen)", "options": ["macht", "mache", "machen", "macht ihr"], "correctIndex": 0, "explanation": "对 ihr 的命令式直接使用 ihr 的动词变位形式，但省去人称代词 ihr，故为 Macht bitte ...！"},
        {"id": "A2_L08_Q4", "type": "GRAMMAR_FILL", "question": "表达身体不适与疼痛的标准第三格句型：'_____ tut der Kopf weh.'", "options": ["Ich", "Mich", "Mir", "Meinem"], "correctIndex": 2, "explanation": "固定句型：jemandem (Dativ) tut etwas weh（某人身体某部位疼痛）。第一人称单数第三格代词为 Mir。"},
        {"id": "A2_L08_Q5", "type": "GRAMMAR_FILL", "question": "医生给出专业建议时，常用情态动词 sollen：'Sie _____ dreimal täglich diese Tablette nehmen.'", "options": ["müssen", "sollen", "dürfen", "wollen"], "correctIndex": 1, "explanation": "sollen 用于转述他人要求或医嘱建议：Sie sollen ... nehmen。"},
        {"id": "A2_L08_Q6", "type": "VOCAB_MEANING", "question": "看病必备词：'das Rezept' 在就医语境下的含义是：", "options": ["烹饪菜谱", "医生开具的处方单 / 药单", "挂号费收据", "病假证明"], "correctIndex": 1, "explanation": "das Rezept 在厨房是菜谱，在医院诊所是医生开具的药品处方单。凭处方去药房 (Apotheke) 取药。"},
        {"id": "A2_L08_Q7", "type": "ARTICLE", "question": "名词 'Krankenversicherung' (医疗保险) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "词尾为 -ung 的复合词必定为阴性名词：die Krankenversicherung。"},
        {"id": "A2_L08_Q8", "type": "VOCAB_MEANING", "question": "突发急救呼叫：在德国拨打急救与消防救援电话号码是：", "options": ["110", "112", "120", "911"], "correctIndex": 1, "explanation": "在全欧盟包括德国，112 是急救救护车 (Rettungsdienst) 和火警电话；110 是报警警察电话 (Polizei)。"},
        {"id": "A2_L08_Q9", "type": "GRAMMAR_FILL", "question": "可分动词的命令式构成：'_____ bitte das Fenster auf!' (aufmachen, 尊称 Sie)", "options": ["Machen Sie", "Aufmachen Sie", "Macht Sie", "Aufmacht Sie"], "correctIndex": 0, "explanation": "尊称命令式变位动词居首，前缀分离并置于句末：Machen Sie bitte das Fenster auf!"},
        {"id": "A2_L08_Q10", "type": "EXAM_REAL", "question": "歌德 A2 写作（向雇主请病假）：'Ich kann heute nicht zur Arbeit kommen, weil ich _____ bin.'", "options": ["müde", "krank", "froh", "hungrig"], "correctIndex": 1, "explanation": "krank sein 意为生病不适；向公司请病假通常还会附上医生开具的病假条 (die Krankschreibung / das Attest)。"}
    ],
    "A2_L09": [
        {"id": "A2_L09_Q1", "type": "GRAMMAR_FILL", "question": "反身代词第四格（第一人称单数）：'Ich freue _____ sehr auf den Urlaub.'", "options": ["mir", "mich", "sich", "dich"], "correctIndex": 1, "explanation": "主语为 ich 时，反身动词 sich freuen 后的一般反身代词第四格为 mich。"},
        {"id": "A2_L09_Q2", "type": "GRAMMAR_FILL", "question": "反身代词第三格辨析：当句中已有第四格直接宾语时：'Ich wasche _____ die Hände.'", "options": ["mich", "mir", "sich", "mein"], "correctIndex": 1, "explanation": "当动作涉及身体某个部位作直接宾语 (die Hände, Akk.) 时，反身代词降为第三格 (Dativ)：Ich wasche mir die Hände (对比: Ich wasche mich)。"},
        {"id": "A2_L09_Q3", "type": "GRAMMAR_FILL", "question": "介词搭配辨析：'sich freuen auf' vs 'sich freuen über'：'Ich freue mich riesig _____ die bestandene Prüfung gestern.'", "options": ["auf", "über", "an", "für"], "correctIndex": 1, "explanation": "sich freuen auf + Akk. 表示对未来将要发生的事充满期待；sich freuen über + Akk. 表示对已经发生或当下的事物感到欣慰高兴。考试已在昨天通过，用 über！"},
        {"id": "A2_L09_Q4", "type": "GRAMMAR_FILL", "question": "反身代词第三人称单复数通用形式：'Er setzt _____ auf den Stuhl.'", "options": ["ihn", "ihm", "sich", "selbst"], "correctIndex": 2, "explanation": "第三人称单复数（er, sie, es, sie, Sie）的反身代词无论三格还是四格一律统称为 sich！"},
        {"id": "A2_L09_Q5", "type": "VOCAB_MEANING", "question": "德语烹饪动词：'braten', 'kochen', 'backen' 含义分别是：", "options": ["煎炸/烤肉、煮/烹饪、烘焙(蛋糕面包)", "煮、炖、切碎", "蒸、炸、腌制", "洗净、搅拌、去皮"], "correctIndex": 0, "explanation": "braten 是煎/炒/烤肉；kochen 是烧水/煮饭做菜；backen 是烤面包或烘焙甜点。"},
        {"id": "A2_L09_Q6", "type": "ARTICLE", "question": "名词 'Trinkgeld' (小费) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "复合名词词性由后半部分决定，das Geld 故 das Trinkgeld。"},
        {"id": "A2_L09_Q7", "type": "GRAMMAR_FILL", "question": "反身代词第二人称单数 (du) 第四格：'Beeil _____ bitte, der Bus kommt gleich!'", "options": ["dich", "dir", "sich", "du"], "correctIndex": 0, "explanation": "sich beeilen（赶快抓紧）支配第四格反身代词，对 du 的命令式中反身代词为 dich：Beeil dich!"},
        {"id": "A2_L09_Q8", "type": "VOCAB_MEANING", "question": "德语传统名菜：'das Schnitzel' 是指：", "options": ["德国烤猪肘", "维也纳风味炸肉排", "德式巴伐利亚白香肠", "德式酸菜肉卷"], "correctIndex": 1, "explanation": "das Schnitzel（炸肉排/维也纳肉排）是德语国家最具代表性的招牌菜肴之一；烤猪肘为 die Schweinshaxe。"},
        {"id": "A2_L09_Q9", "type": "GRAMMAR_FILL", "question": "介词搭配：'sich interessieren _____ Kunst.'", "options": ["an", "über", "für", "auf"], "correctIndex": 2, "explanation": "固定搭配：sich interessieren für + Akkusativ（对……感兴趣）。"},
        {"id": "A2_L09_Q10", "type": "EXAM_REAL", "question": "歌德 A2 餐厅交际：想表达“菜品非常可口美味”时最自然的口语是：", "options": ["Das Essen hat mir sehr gut geschmeckt.", "Das Essen hat mir gefallen.", "Das Essen ist teuer.", "Ich will nicht mehr."], "correctIndex": 0, "explanation": "形容食物美味在德语中使用 schmecken：Das Essen schmeckt (mir) sehr gut / hat sehr gut geschmeckt。gefallen 则用于评价外表美观。"}
    ],
    "A2_L10": [
        {"id": "A2_L10_Q1", "type": "GRAMMAR_FILL", "question": "零冠词（无冠词 Typ III）阳性第四格形容词词尾：'Ich trinke morgens gern _____ Kaffee.' (schwarz)", "options": ["schwarzer", "schwarzen", "schwarzes", "schwarze"], "correctIndex": 1, "explanation": "在没有冠词的情况下，形容词词尾必须承担起定冠词的格标记（强变化）。阳性第四格定冠词为 den，故形容词词尾为 -en：schwarzen Kaffee。"},
        {"id": "A2_L10_Q2", "type": "GRAMMAR_FILL", "question": "零冠词中性第一格形容词词尾：'Hier steht _____ Bier.' (kalt)", "options": ["kalter", "kalte", "kaltes", "kalten"], "correctIndex": 2, "explanation": "无冠词时，中性第一格需体现 das 的标志 -es：kaltes Bier。"},
        {"id": "A2_L10_Q3", "type": "GRAMMAR_FILL", "question": "零冠词阴性第一格形容词词尾：'_____ Milch ist gesund.' (frisch)", "options": ["Frischer", "Frische", "Frisches", "Frischen"], "correctIndex": 1, "explanation": "无冠词时，阴性第一格需体现 die 的标志 -e：Frische Milch。"},
        {"id": "A2_L10_Q4", "type": "GRAMMAR_FILL", "question": "零冠词复数第一/四格形容词词尾：'Ich kaufe _____ Äpfel.' (rot)", "options": ["roten", "rote", "roter", "rotes"], "correctIndex": 1, "explanation": "无冠词时，复数第一/四格体现 die 的标志 -e：rote Äpfel。"},
        {"id": "A2_L10_Q5", "type": "GRAMMAR_FILL", "question": "零冠词第三格阳性形容词词尾：'Er trinkt Tee mit _____ Zucker.' (weiß)", "options": ["weißem", "weißen", "weißer", "weißes"], "correctIndex": 0, "explanation": "介词 mit 支配第三格，阳性第三格冠词为 dem，故无冠词时形容词加 -em：mit weißem Zucker。"},
        {"id": "A2_L10_Q6", "type": "VOCAB_MEANING", "question": "性格品质形容词：'zuverlässig' 的中文意思是：", "options": ["轻浮自私的", "诚实可靠的 / 值得信赖的", "暴躁易怒的", "内向害羞的"], "correctIndex": 1, "explanation": "zuverlässig 意为靠谱的、值得信任的；其反义词为 unzuverlässig。"},
        {"id": "A2_L10_Q7", "type": "ARTICLE", "question": "名词 'Anzug' (男士西装) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "Anzug 是阳性名词：der Anzug (Pl. die Anzüge)；女士套装为 das Kostüm。"},
        {"id": "A2_L10_Q8", "type": "GRAMMAR_FILL", "question": "衣着搭配动词辨析：'Der Mantel _____ dir ausgezeichnet!'", "options": ["passt", "steht", "gehört", "sitzt"], "correctIndex": 1, "explanation": "jemandem stehen 指衣服在颜色、气质、款式上“衬托某人好看”；jemandem passen 指尺码尺寸合适。"},
        {"id": "A2_L10_Q9", "type": "SENTENCE_BUILDER", "question": "形容人外貌：'Er hat ein _____ Gesicht und _____ Haare.' (rund / blond)", "options": ["rundes / blonde", "runde / blonden", "rundem / blonder", "runden / blondes"], "correctIndex": 0, "explanation": "中性第四格 ein rundes Gesicht；复数零冠词第四格 blonde Haare。"},
        {"id": "A2_L10_Q10", "type": "EXAM_REAL", "question": "试穿衣服时问售货员“有大一号的吗？”的德语表达是：", "options": ["Haben Sie das eine Nummer größer?", "Haben Sie das zu klein?", "Kostet das mehr Geld?", "Wie gefällt Ihnen das?"], "correctIndex": 0, "explanation": "'Haben Sie das eine Nummer größer / kleiner?' 是商场服装购物最地道的换尺码句型。"}
    ],
    "A2_L11": [
        {"id": "A2_L11_Q1", "type": "GRAMMAR_FILL", "question": "过程被动态现在时 (Vorgangspassiv Präsens) 的基本结构是：", "options": ["haben + Partizip II", "sein + Partizip II", "werden + Partizip II", "würde + Infinitiv"], "correctIndex": 2, "explanation": "德语过程被动态的构成公式为：助动词 werden (人称变位) + 第二分词 (Partizip II) 置于句末。"},
        {"id": "A2_L11_Q2", "type": "GRAMMAR_FILL", "question": "被动态填空：'Das alte Theater _____ zurzeit renoviert.'", "options": ["wird", "werde", "wurde", "worden"], "correctIndex": 0, "explanation": "主语 Das Theater 为第三人称单数，现在时 werden 变位为 wird。"},
        {"id": "A2_L11_Q3", "type": "GRAMMAR_FILL", "question": "被动态中的施动者（由谁完成动作）通常用哪个介词引出：'Der Roman wurde _____ einem berühmten Autor geschrieben.'", "options": ["durch", "von", "bei", "mit"], "correctIndex": 1, "explanation": "施动的主体人或施动者通常用介词 von + Dativ 引出；媒介或手段多用 durch + Akkusativ。"},
        {"id": "A2_L11_Q4", "type": "GRAMMAR_FILL", "question": "动词 werden 的第二人称单数 (du) 变位是：'Du _____ morgen abgeholt.'", "options": ["wirst", "werdest", "wird", "wurdest"], "correctIndex": 0, "explanation": "werden 的现在时第二人称单数变位为 wirst（发生换音 e -> i）。"},
        {"id": "A2_L11_Q5", "type": "VOCAB_MEANING", "question": "文化展览术语：'die Ausstellung' 的意思是：", "options": ["音乐会", "艺术展览 / 展会", "电影首映礼", "戏剧表演"], "correctIndex": 1, "explanation": "die Ausstellung 意为展览会（如 Kunstausstellung 艺术展），动词为 ausstellen（展出）。"},
        {"id": "A2_L11_Q6", "type": "ARTICLE", "question": "名词 'Gemälde' (画作、油画) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "带有 Ge- 前缀的集合名词多为中性：das Gemälde (Pl. die Gemälde)。"},
        {"id": "A2_L11_Q7", "type": "GRAMMAR_FILL", "question": "将主动句转为被动句：'Man schließt das Museum um 18 Uhr.' -> 'Das Museum _____ um 18 Uhr _____.'", "options": ["wird / geschlossen", "ist / geschlossen", "hat / geschlossen", "wurde / geschlossen"], "correctIndex": 0, "explanation": "原句现在时，转为被动句使用 wird + 第二分词 geschlossen。"},
        {"id": "A2_L11_Q8", "type": "VOCAB_MEANING", "question": "票务用语：'Ermäßigung für Studenten' 的中文含义是：", "options": ["学生免费进场", "学生优惠打折票", "仅限学生预约", "学生专场演出"], "correctIndex": 1, "explanation": "die Ermäßigung 指票价减免、优惠打折；ermäßigt 指优惠价格。"},
        {"id": "A2_L11_Q9", "type": "SENTENCE_BUILDER", "question": "被动态句子框架排列：'Hier / Deutsch / sprechen (被动)'", "options": ["Hier Deutsch wird gesprochen.", "Hier wird Deutsch gesprochen.", "Hier Deutsch gesprochen wird.", "Deutsch hier wird gesprochen."], "correctIndex": 1, "explanation": "变位助动词 wird 居第 2 位，第二分词 gesprochen 置于句末构成被动框架。"},
        {"id": "A2_L11_Q10", "type": "EXAM_REAL", "question": "歌德 A2 阅读通告：'Montags Ruhetag' 贴在博物馆门口意味着：", "options": ["周一票价半价", "周一闭馆休息，不对外开放", "周一举办特展", "周一仅限会员参观"], "correctIndex": 1, "explanation": "Ruhetag 是德语区餐饮、零售与博物馆的“公休日、休息日”，Montags Ruhetag 即“每周一闭馆/不营业”。"}
    ],
    "A2_L12": [
        {"id": "A2_L12_Q1", "type": "GRAMMAR_FILL", "question": "第一格关系代词填空：'Der Mann, _____ dort drüben steht, ist mein Deutschlehrer.' (阳性 der Mann)", "options": ["der", "den", "dem", "dessen"], "correctIndex": 0, "explanation": "先行词是阳性单数 der Mann，在关系从句中作主语（第一格），故关系代词为 der。"},
        {"id": "A2_L12_Q2", "type": "GRAMMAR_FILL", "question": "第四格关系代词填空：'Der Film, _____ wir gestern gesehen haben, war sehr spannend.' (阳性 der Film)", "options": ["der", "den", "dem", "das"], "correctIndex": 1, "explanation": "先行词是阳性单数 der Film，在关系从句中作及物动词 sehen 的宾语（第四格），故用 den。"},
        {"id": "A2_L12_Q3", "type": "GRAMMAR_FILL", "question": "中性关系代词填空：'Das Buch, _____ auf dem Tisch liegt, gehört mir.'", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "先行词为中性 das Buch，从句中作第一格主语，关系代词为 das。"},
        {"id": "A2_L12_Q4", "type": "GRAMMAR_FILL", "question": "阴性关系代词填空：'Die Frau, _____ ich gestern im Supermarkt getroffen habe, ist meine Nachbarin.'", "options": ["der", "die", "den", "das"], "correctIndex": 1, "explanation": "先行词为阴性 die Frau，在从句中作第四格宾语，阴性第四格关系代词依然是 die。"},
        {"id": "A2_L12_Q5", "type": "VOCAB_MEANING", "question": "德国环保核心国策：'die Mülltrennung' 的意思是：", "options": ["垃圾焚烧发电", "严格的垃圾分类", "填埋有害垃圾", "禁止使用塑料袋"], "correctIndex": 1, "explanation": "die Mülltrennung 意为垃圾分类。德国日常将生活垃圾细分为纸类(Blaue Tonne)、有机垃圾(Biomüll)、塑料包装(Gelber Sack)及残余垃圾(Restmüll)。"},
        {"id": "A2_L12_Q6", "type": "ARTICLE", "question": "名词 'Klimawandel' (气候变化) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "复合名词后半部分为 der Wandel（变迁、转变），故整体为阳性：der Klimawandel。"},
        {"id": "A2_L12_Q7", "type": "VOCAB_MEANING", "question": "德国超市随处可见的饮料瓶押金制度称为：", "options": ["das Pfand / das Pfandsystem", "die Steuer", "der Rabatt", "die Strafe"], "correctIndex": 0, "explanation": "das Pfand 是押金，在德国购买瓶装水或啤酒会预收 0.08 到 0.25 欧元瓶子押金，退瓶机扫描后退还。"},
        {"id": "A2_L12_Q8", "type": "GRAMMAR_FILL", "question": "复数关系代词第一格填空：'Die Leute, _____ in dieser Straße wohnen, sind sehr umweltbewusst.'", "options": ["die", "denen", "der", "welche"], "correctIndex": 0, "explanation": "先行词是复数 Die Leute，在从句中作主语，复数第一格关系代词为 die。"},
        {"id": "A2_L12_Q9", "type": "SENTENCE_BUILDER", "question": "关系从句的语序铁律是：", "options": ["变位动词紧跟关系代词之后", "变位动词必须置于关系从句的绝对句末", "变位动词与主句动词合并", "关系代词后不用逗号"], "correctIndex": 1, "explanation": "关系从句属于从属从句，主句与从句之间必有逗号隔开，从句变位动词强制置于句尾。"},
        {"id": "A2_L12_Q10", "type": "EXAM_REAL", "question": "歌德 A2 环保倡议口号：'Schützen Sie die Umwelt!' 动词 schützen 的含义是：", "options": ["破坏、污染", "保护、守护", "测量、观察", "改变、适应"], "correctIndex": 1, "explanation": "schützen 意为保护；die Umwelt schützen 即保护环境。"}
    ],
    "A2_L13": [
        {"id": "A2_L13_Q1", "type": "GRAMMAR_FILL", "question": "第二虚拟式 (Konjunktiv II) 表示极礼貌请求：'_____ Sie mir bitte helfen?' (können)", "options": ["Können", "Könnten", "Konnten", "Kann"], "correctIndex": 1, "explanation": "könnten Sie ...? 比普通陈述语气 können Sie ...? 更加客气、谦逊委婉，是德语请求助力的金牌表达。"},
        {"id": "A2_L13_Q2", "type": "GRAMMAR_FILL", "question": "第二虚拟式 würde + 动词原形表达愿望：'Ich _____ gern nach Hamburg reisen.'", "options": ["werde", "würde", "wurde", "worden"], "correctIndex": 1, "explanation": "würde + Infinitiv 是第二虚拟式的万能替代形式，表达主观意愿或礼貌设想。第一人称单数为 ich würde。"},
        {"id": "A2_L13_Q3", "type": "GRAMMAR_FILL", "question": "第二虚拟式 haben 的形式：'Wenn ich mehr Zeit _____, würde ich einen Deutschkurs machen.'", "options": ["habe", "hatte", "hätte", "hätten"], "correctIndex": 2, "explanation": "haben 的第二虚拟式带变音为 hätte。第一/第三人称单数同形：ich hätte, er hätte。"},
        {"id": "A2_L13_Q4", "type": "GRAMMAR_FILL", "question": "第二虚拟式 sein 的形式：'Das _____ super! (那要是那样就太棒了！)'", "options": ["ist", "wäre", "war", "sei"], "correctIndex": 1, "explanation": "sein 的第二虚拟式为 wäre (es wäre super / toll)。"},
        {"id": "A2_L13_Q5", "type": "VOCAB_MEANING", "question": "数字社交网络术语：'das Passwort' 的中文含义是：", "options": ["用户名", "电子邮箱", "账户密码", "手机验证码"], "correctIndex": 2, "explanation": "das Passwort 意为密码；der Benutzername 为用户名。"},
        {"id": "A2_L13_Q6", "type": "ARTICLE", "question": "名词 'Nachricht' (消息、新闻、微信信息) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "Nachricht 是阴性名词：die Nachricht (Pl. die Nachrichten)。"},
        {"id": "A2_L13_Q7", "type": "GRAMMAR_FILL", "question": "第二虚拟式情态动词 dürfen 表示委婉询问许可：'_____ ich Sie kurz etwas fragen?'", "options": ["Darf", "Dürfte", "Durfte", "Dürfen"], "correctIndex": 1, "explanation": "Dürfte ich ...? 比 Darf ich ...? 更加客气礼貌，意为“可否冒昧请教您一个问题？”。"},
        {"id": "A2_L13_Q8", "type": "VOCAB_MEANING", "question": "网络操作动词：'herunterladen' 与 'hochladen' 分别表示：", "options": ["关机与开机", "下载与上传", "刷新与保存", "删除与复制"], "correctIndex": 1, "explanation": "herunterladen (或 downloaden) 意为下载；hochladen (或 uploaden) 意为上传。"},
        {"id": "A2_L13_Q9", "type": "SENTENCE_BUILDER", "question": "委婉表达愿望选出正确形式：'Ich _____ jetzt gern am Strand!'", "options": ["bin", "wäre", "war", "werde"], "correctIndex": 1, "explanation": "Ich wäre jetzt gern am Strand!（我现在要是能在海滩该多惬意啊！）表达不符合现实的主观美好憧憬。"},
        {"id": "A2_L13_Q10", "type": "EXAM_REAL", "question": "歌德 A2 电话留言：'Könnten Sie mich bitte zurückrufen?' 意思是：", "options": ["您可以稍后再打来吗？", "您能给我回个电话吗？", "请问您找哪一位？", "对不起打错了。"], "correctIndex": 1, "explanation": "zurückrufen 意为“给某人回电话”，这是电话留言录音机中最地道实用的句型。"}
    ],
    "A2_L14": [
        {"id": "A2_L14_Q1", "type": "GRAMMAR_FILL", "question": "双宾语语序规则（两个名词时）：'Die Mutter schenkt _____ (der Sohn) _____ (ein Fahrrad).' ", "options": ["dem Sohn ein Fahrrad", "ein Fahrrad dem Sohn", "den Sohn ein Fahrrad", "einem Fahrrad der Sohn"], "correctIndex": 0, "explanation": "双宾语铁律一：当两个宾语都是名词时，第三格名词（人/物）在前，第四格名词在后：schenkt dem Sohn (Dat.) ein Fahrrad (Akk.)。"},
        {"id": "A2_L14_Q2", "type": "GRAMMAR_FILL", "question": "双宾语语序规则（代词与名词搭配）：'Die Mutter schenkt _____ (代词 ihn 指指代 der Ball) _____ (der Junge).' ", "options": ["dem Jungen ihn", "ihn dem Jungen", "ihm den Ball", "ihn ihn"], "correctIndex": 1, "explanation": "双宾语铁律二：只要出现代词，代词永远先于名词！哪怕代词是第四格宾语，也排在第三格名词之前：schenkt ihn (Akk. Pron.) dem Jungen (Dat. Noun)。"},
        {"id": "A2_L14_Q3", "type": "GRAMMAR_FILL", "question": "双宾语语序规则（两个都为代词时）：'Sie schenkt _____ (es = das Buch) _____ (ihm = der Vater).' ", "options": ["ihm es", "es ihm", "ihm ihn", "er ihm"], "correctIndex": 1, "explanation": "双宾语铁律三：当两个宾语全都是人称代词时，第四格代词必须绝对排在第三格代词之前！即：es ihm (Akk. vor Dat.)！口诀：代代相传四在前！"},
        {"id": "A2_L14_Q4", "type": "VOCAB_MEANING", "question": "德国传统节日文化：'der Adventskalender' 的特点是：", "options": ["复活节彩蛋篮", "从12月1日到24日每天打开一个小格拿礼物的圣诞降临历", "慕尼黑啤酒节排期表", "元旦新年倒数日历"], "correctIndex": 1, "explanation": "der Adventskalender（降临节日历）是德国儿童在12月圣诞节前每天打开一格拆小巧克力的传统风俗。"},
        {"id": "A2_L14_Q5", "type": "ARTICLE", "question": "名词 'Geschenk' (礼物) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "Geschenk 是中性名词：das Geschenk (Pl. die Geschenke)。"},
        {"id": "A2_L14_Q6", "type": "VOCAB_MEANING", "question": "德语生日与新年祝福语搭配：'Herzlichen Glückwunsch zum Geburtstag!' 对应哪个节日？", "options": ["新年元旦", "复活节", "生日快乐", "婚礼志禧"], "correctIndex": 2, "explanation": "der Geburtstag 是生日，整句意为“衷心祝贺生日快乐！”。新年祝福常说 'Frohes neues Jahr!'。"},
        {"id": "A2_L14_Q7", "type": "EXAM_REAL", "question": "受邀去德国家庭做客参加晚宴，最得体的做客礼仪是：", "options": ["两手空空直接入席", "带一束花或一瓶优质葡萄酒作为伴手礼并准时到达", "故意迟到一个小时以示低调", "饭前直接索要WiFi密码打游戏"], "correctIndex": 1, "explanation": "在德国做客，准时 (Pünktlichkeit) 极其重要，且通常会给女主人带鲜花或主人带一瓶酒作为礼貌礼物 (Gastgeschenk)。"},
        {"id": "A2_L14_Q8", "type": "GRAMMAR_FILL", "question": "双宾语代词替换练习：'Er gibt seiner Schwester den Schlüssel.' 替换为两个代词后是：", "options": ["Er gibt ihr ihn.", "Er gibt ihn ihr.", "Er gibt ihn sie.", "Er gibt sie ihm."], "correctIndex": 1, "explanation": "den Schlüssel (Akk.) 变为 ihn；seiner Schwester (Dat.) 变为 ihr。两代词并列时四格在前：Er gibt ihn ihr。"},
        {"id": "A2_L14_Q9", "type": "VOCAB_MEANING", "question": "德国狂欢节（Fasching / Karneval）在哪个城市最为狂欢盛大？", "options": ["Köln (科隆)", "Frankfurt (法兰克福)", "Hamburg (汉堡)", "Bonn (波恩)"], "correctIndex": 0, "explanation": "科隆狂欢节 (Kölner Karneval) 是德国乃至欧洲规模最宏大、历史最悠久的狂欢庆典之一，俗称“第五季节”。"},
        {"id": "A2_L14_Q10", "type": "EXAM_REAL", "question": "遇到朋友打喷嚏时，德语国家习惯立刻对他说：", "options": ["Guten Appetit!", "Gesundheit!", "Herzlich willkommen!", "Viel Glück!"], "correctIndex": 1, "explanation": "德语习惯在他人打喷嚏后回应 'Gesundheit!'（祝您健康！）。"}
    ],
    "A2_L15": [
        {"id": "A2_L15_Q1", "type": "EXAM_REAL", "question": "歌德 A2 听力理解要领：听广播寻人/车站通知时，最核心的技巧是：", "options": ["试图听懂广播中每一个辅音和单词", "抓取关键信号词（站台号、列车班次、改道、时间）以及第一句与结尾总结句", "只要听见熟悉的词就立刻选对应选项", "完全不用看题干选项"], "correctIndex": 1, "explanation": "歌德 A2 听力需要先快速审读题干设问，听音时针对性捕捉数字、站台、改期等关键词汇，注意防范后半句 aber / leider 等转折陷阱。"},
        {"id": "A2_L15_Q2", "type": "EXAM_REAL", "question": "歌德 A2 阅读匹配题（Teil 3）：为用户需求匹配广告信息，若某条需求完全没有对应广告，应选择：", "options": ["随便蒙一个", "选 X (keine Anzeige passt)", "选第一个广告", "选最后一个广告"], "correctIndex": 1, "explanation": "歌德 A2 阅读配对题中，若无任何广告与某项需求匹配，标准答案选项即为“X”。"},
        {"id": "A2_L15_Q3", "type": "EXAM_REAL", "question": "歌德 A2 书面表达（Teil 1 短信/便条）：题目要求包含 3 个要点 (Leitpunkte)，写作时：", "options": ["任选 1 个要点展开写长即可", "必须逐一覆盖所有 3 个要点，且字数通常在 30-40 词左右", "不需要称谓与结语", "全部抄写题目说明"], "correctIndex": 1, "explanation": "歌德写作评分规则极其严格，遗漏任何一个指定要点都会被严重扣分；且必须有标准的打招呼和结尾致意。"},
        {"id": "A2_L15_Q4", "type": "EXAM_REAL", "question": "歌德 A2 口语考试（Teil 2 谈论自身经历）：抽到卡片 'Hobbys'，较好的回答句式是：", "options": ["Ich weiß nicht.", "In meiner Freizeit spiele ich sehr gern Fußball und höre Musik.", "Fußball ist gut.", "Nein danke."], "correctIndex": 1, "explanation": "A2 口语应能用简单完整的复合句流畅表达个人生活与喜好：In meiner Freizeit + 动词 + gern ...。"},
        {"id": "A2_L15_Q5", "type": "EXAM_REAL", "question": "歌德 A2 口语（Teil 3 协商约定计划）：对方提议 'Wollen wir am Samstag ins Kino gehen?'，如果你没空，得体回应是：", "options": ["Nein, ich mag dich nicht.", "Am Samstag kann ich leider nicht, aber wie wäre es mit Sonntag?", "Samstag ist verboten.", "Ich habe kein Geld."], "correctIndex": 1, "explanation": "委婉拒绝并主动提出替代方案：... kann ich leider nicht, aber wie wäre es mit ...?（……我很抱歉去不了，但是周日怎么样呢？）。"},
        {"id": "A2_L15_Q6", "type": "GRAMMAR_FILL", "question": "综合语法检阅：'Er lernt fleißig Deutsch, _____ er in Deutschland eine Ausbildung machen will.'", "options": ["dass", "weil", "ob", "wenn"], "correctIndex": 1, "explanation": "后半句陈述学德语的因果动机与目的，用从属因果连词 weil，动词 will 置于句末。"},
        {"id": "A2_L15_Q7", "type": "GRAMMAR_FILL", "question": "综合形容词词尾检阅：'Der jung_____ Mann hilft einer alt_____ Dame.'", "options": ["-e / -en", "-er / -er", "-en / -e", "-es / -en"], "correctIndex": 0, "explanation": "定冠词阳性第一格：der junge Mann (-e)；定冠词阴性第三格：einer alten Dame (-en)。"},
        {"id": "A2_L15_Q8", "type": "GRAMMAR_FILL", "question": "综合过去时检阅：'Gestern _____ wir im Museum und _____ viele berühmte Bilder gesehen.'", "options": ["waren / haben", "sind / hatten", "hatten / waren", "wurden / sind"], "correctIndex": 0, "explanation": "句一 sein 过去时用 waren；句二 sehen 的完成时助动词用 haben (haben ... gesehen)。"},
        {"id": "A2_L15_Q9", "type": "VOCAB_MEANING", "question": "考试通知术语：'die Teilnahmebestätigung' 意思是：", "options": ["缺考通知单", "参课证明 / 参加确认书", "补考罚单", "最终学位证书"], "correctIndex": 1, "explanation": "die Teilnahme 参加 + die Bestätigung 确认/证明 = 参课证明或活动参与确认函。"},
        {"id": "A2_L15_Q10", "type": "EXAM_REAL", "question": "歌德 A2 考试总分 100 分，及格通过线 (Bestanden) 通常是：", "options": ["50 分", "60 分 (60%)", "75 分", "85 分"], "correctIndex": 1, "explanation": "歌德各级别标准及格线通常为满分的 60%（即 60分及以上为及格通过 Bestanden）。"}
    ]
}
