#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive Quiz Bank for Level B1 (Goethe B1 Exam Standard):
15 Lessons, 10 in-depth questions per lesson = 150 total questions.
Covers obwohl vs trotzdem, Infinitiv mit zu, Passiv (Präteritum & Perfekt),
Genitiv-Präpositionen (wegen, trotz, während, statt), Konjunktiv II Vergangenheit,
um...zu vs damit, Pronominaladverbien (da(r)- / wo(r)-), Passiversatzformen (sein+zu),
Partizipien als Adjektive, unpersönliches Passiv, Relativsätze mit Präpositionen,
temporale Konnektoren, indirekte Rede (Konjunktiv I), Funktionsverbgefüge, and Goethe B1 exam training.
"""

B1_QUIZZES = {
    "B1_L01": [
        {"id": "B1_L01_Q1", "type": "GRAMMAR_FILL", "question": "让步连词辨析（从属从句 vs 主句副词连接词）：'_____ es regnet, gehen wir spazieren.'", "options": ["Obwohl", "Trotzdem", "Deshalb", "Weil"], "correctIndex": 0, "explanation": "obwohl 是从属连词，引导让步从句（动词 regnet 置于从句末尾）；trotzdem 则是副词/主句连词，要求动词位于其后第 2 位。"},
        {"id": "B1_L01_Q2", "type": "GRAMMAR_FILL", "question": "副词 trotzdem 的语序规律：'Es regnet. _____ gehen wir spazieren.'", "options": ["Obwohl", "Trotzdem", "Weil", "Dass"], "correctIndex": 1, "explanation": "trotzdem 引导独立主句，占句首第 1 位，紧接变位动词 gehen 占第 2 位：Trotzdem gehen wir ...。"},
        {"id": "B1_L01_Q3", "type": "GRAMMAR_FILL", "question": "时间/让步对比连词 während：'Er lernt fleißig, _____ sein Bruder nur faulenzt.'", "options": ["während", "trotzdem", "damit", "obwohl"], "correctIndex": 0, "explanation": "während 引导对比从句（表示“而……与此相反”），动词 faulenzt 置于从句末尾。"},
        {"id": "B1_L01_Q4", "type": "VOCAB_MEANING", "question": "人际心理学核心词：'der Konflikt / die Meinungsverschiedenheit' 含义是：", "options": ["友好合作 / 共同目标", "矛盾冲突 / 意见分歧", "信任危机 / 抑郁", "恋爱关系 / 婚姻誓言"], "correctIndex": 1, "explanation": "der Konflikt 指冲突、争端；die Meinungsverschiedenheit 指意见不一、分歧。"},
        {"id": "B1_L01_Q5", "type": "GRAMMAR_FILL", "question": "动词 kompromissbereit 的名词形式是：'Wir müssen einen _____ finden.'", "options": ["Kompromiss", "Konflikt", "Vertrag", "Zweifel"], "correctIndex": 0, "explanation": "einen Kompromiss finden / schließen 是德语解决分歧的经典固定短语，意为“达成妥协/折中方案”。"},
        {"id": "B1_L01_Q6", "type": "SENTENCE_BUILDER", "question": "选出语序完全正确的尽管...但是...复合句：", "options": ["Obwohl er krank war, ging er trotzdem zur Arbeit.", "Obwohl er war krank, er ging zur Arbeit.", "Trotzdem er krank war, ging er zur Arbeit.", "Obwohl er krank ging er zur Arbeit war."], "correctIndex": 0, "explanation": "从句 Obwohl er krank war（动词在句末），主句倒装 ging er ...，句中可带 trotzdem 加强转折语气。"},
        {"id": "B1_L01_Q7", "type": "ARTICLE", "question": "名词 'Beziehung' (人际关系、恋爱关系) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "以 -ung 结尾的名词必为阴性名词：die Beziehung (Pl. die Beziehungen)。"},
        {"id": "B1_L01_Q8", "type": "VOCAB_MEANING", "question": "沟通技巧：'Kritik annehmen' 的中文含义是：", "options": ["提出激烈批评", "虚心接受批评意见", "拒绝认错", "避免争论"], "correctIndex": 1, "explanation": "Kritik annehmen 指接受、接纳他人的批评；Kritik üben 则指提出批评。"},
        {"id": "B1_L01_Q9", "type": "GRAMMAR_FILL", "question": "形容词 eifersüchtig 的固定介词搭配：'Er ist sehr eifersüchtig _____ seinen Kollegen.'", "options": ["auf", "über", "an", "für"], "correctIndex": 0, "explanation": "固定介词搭配：eifersüchtig sein auf + Akkusativ（嫉妒/吃……的醋）。"},
        {"id": "B1_L01_Q10", "type": "EXAM_REAL", "question": "歌德 B1 口语表达自身观点经典套话：", "options": ["Meiner Meinung nach sollte man Kompromisse eingehen.", "Ich bin sicher, dass du falsch bist.", "Du musst mir zustimmen.", "Das ist mir ganz egal."], "correctIndex": 0, "explanation": "'Meiner Meinung nach + 动词 ...'（依我之见……）是歌德 B1 表达个人观点的最高频黄金开篇句型。"}
    ],
    "B1_L02": [
        {"id": "B1_L02_Q1", "type": "GRAMMAR_FILL", "question": "带 zu 不定式短语：'Ich habe vor, nächste Woche eine Reise nach Wien _____.' (machen)", "options": ["machen", "zu machen", "gemacht", "machend"], "correctIndex": 1, "explanation": "固定句型 vorhaben (计划打算) 要求后接带 zu 不定式：vorhaben, ... zu machen。"},
        {"id": "B1_L02_Q2", "type": "GRAMMAR_FILL", "question": "可分动词的带 zu 不定式形态：'Es ist wichtig, pünktlich _____.' (aufstehen)", "options": ["zu aufstehen", "aufzustehen", "aufstehen zu", "aufgestanden"], "correctIndex": 1, "explanation": "可分动词在构成带 zu 不定式时，zu 必须嵌入前缀与词干之间：auf + zu + stehen -> aufzustehen。"},
        {"id": "B1_L02_Q3", "type": "GRAMMAR_FILL", "question": "情态动词替代句型 brauchen ... nicht zu：'Du musst nicht kommen.' 等同于：'Du _____ nicht _____.' (kommen)", "options": ["musst / zu kommen", "brauchst / zu kommen", "darfst / zu kommen", "sollst / zu kommen"], "correctIndex": 1, "explanation": "口诀：'Wer brauchen ohne zu gebraucht, braucht brauchen gar nicht zu gebrauchen.' brauchen + nicht + zu 不定式等同于 nicht müssen（不必做某事）。"},
        {"id": "B1_L02_Q4", "type": "GRAMMAR_FILL", "question": "半情态动词 scheinen 的带 zu 结构：'Er scheint die Prüfung bestanden _____.' (haben)", "options": ["haben", "zu haben", "gehabt", "hätte"], "correctIndex": 1, "explanation": "scheinen + zu + Infinitiv 表推测“似乎、好像”：Er scheint ... bestanden zu haben（他似乎已经通过了考试）。"},
        {"id": "B1_L02_Q5", "type": "VOCAB_MEANING", "question": "德国大学学术术语：'die Vorlesung' 与 'das Seminar' 的区别是：", "options": ["大课讲座（教授主讲） vs 讨论班/研讨课（师生互动研讨）", "闭卷考试 vs 开卷考试", "本科学位 vs 硕士学位", "实验课 vs 体育选修课"], "correctIndex": 0, "explanation": "die Vorlesung 是大阶梯教室教授讲授的大课；das Seminar 是小班研讨课，要求学生作报告 (Referat) 并参与学术讨论。"},
        {"id": "B1_L02_Q6", "type": "ARTICLE", "question": "名词 'Stipendium' (奖学金) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "拉丁源中性词 -um 结尾，定冠词必为 das：das Stipendium (Pl. die Stipendien)。"},
        {"id": "B1_L02_Q7", "type": "GRAMMAR_FILL", "question": "不带 zu 的动词辨析：以下哪个动词后接动词原形且【绝不能】加 zu？", "options": ["hoffen", "planen", "können", "vergessen"], "correctIndex": 2, "explanation": "纯情态动词（können, müssen, dürfen, sollen, wollen, mögen）以及 hören, sehen, lassen 后接动词原形，绝不能加 zu！"},
        {"id": "B1_L02_Q8", "type": "VOCAB_MEANING", "question": "学术科研动词：'eine wissenschaftliche Arbeit verfassen' 意思是：", "options": ["宣读录取通知书", "撰写学术论文", "批改试卷", "发表口头演讲"], "correctIndex": 1, "explanation": "verfassen 意为撰写、著述；eine wissenschaftliche Arbeit verfassen 即撰写学术论文。"},
        {"id": "B1_L02_Q9", "type": "SENTENCE_BUILDER", "question": "带 zu 不定式复合句排列：'Ich freue mich darauf, _____.' (dich / bald / wiedersehen)", "options": ["dich bald wiederzusehen", "dich bald zu wiedersehen", "bald wiedersehen zu dich", "zu sehen dich wieder"], "correctIndex": 0, "explanation": "wiedersehen 是可分动词，在不定式短语中写为 wiederzusehen，宾语 dich 及状语置于其前。"},
        {"id": "B1_L02_Q10", "type": "EXAM_REAL", "question": "歌德 B1 大学科研报告 (Referat) 开场白规范：", "options": ["Das Thema meiner heutigen Präsentation lautet ...", "Ich will euch was sagen.", "Heute sprechen wir über alles.", "Keine Ahnung, was ich sage."], "correctIndex": 0, "explanation": "'Das Thema meiner Präsentation lautet ...' 是学术报告作 Presentation 最严谨得体的标准破题导入语。"}
    ],
    "B1_L03": [
        {"id": "B1_L03_Q1", "type": "GRAMMAR_FILL", "question": "过去时被动态 (Passiv Präteritum) 构成：助动词 werden 过去时形式是：'Das Gebäude _____ 1990 erbaut.'", "options": ["wird", "wurde", "worden", "geworden"], "correctIndex": 1, "explanation": "被动态过去时构成公式为：wurde / wurden + 第二分词。主语 Das Gebäude 为单数，故用 wurde。"},
        {"id": "B1_L03_Q2", "type": "GRAMMAR_FILL", "question": "完成时被动态 (Passiv Perfekt) 铁律：助动词 sein + 第二分词 + _____：'Der Brief ist gestern abgeschickt _____.'", "options": ["geworden", "worden", "wurde", "werden"], "correctIndex": 1, "explanation": "在被动态现在完成时中，werden 的第二分词必须省去 ge- 前缀，固定形式为 worden（而非 *geworden）！句式：ist ... abgeschickt worden。"},
        {"id": "B1_L03_Q3", "type": "GRAMMAR_FILL", "question": "介词辨析（介质/渠道 durch vs 行为主体 von）：'Die Nachricht wurde _____ das Radio verbreitet.'", "options": ["von", "durch", "bei", "mit"], "correctIndex": 1, "explanation": "广播(das Radio)是传播消息的渠道或媒介媒介，应用 durch + Akkusativ；若是某记者传播，则用 von + Dativ。"},
        {"id": "B1_L03_Q4", "type": "VOCAB_MEANING", "question": "德语职场招聘核心词：'die Stellenausschreibung' 意思是：", "options": ["职位招聘启事 / 岗位招募公告", "辞职信", "试用期合同", "岗位调动单"], "correctIndex": 0, "explanation": "die Stelle（职位）+ ausschreiben（公开招募）= 岗位招聘启事。"},
        {"id": "B1_L03_Q5", "type": "ARTICLE", "question": "名词 'Vorstellungsgespräch' (求职面试) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "以 das Gespräch（谈话）结尾的复合名词必为中性：das Vorstellungsgespräch。"},
        {"id": "B1_L03_Q6", "type": "GRAMMAR_FILL", "question": "将现在完成时主动句变为完成时被动态：'Man hat die Daten gelöscht.' -> 'Die Daten _____ gelöscht _____.'", "options": ["sind / worden", "haben / worden", "wurden / worden", "sind / geworden"], "correctIndex": 0, "explanation": "Die Daten 是复数，被动完成时助动词用 sein (sind) + Partizip II (gelöscht) + worden。"},
        {"id": "B1_L03_Q7", "type": "VOCAB_MEANING", "question": "职场薪酬待遇术语：'das Bruttogehalt' vs 'das Nettogehalt' 区别是：", "options": ["税前总薪资 vs 扣除税费及社保后的税后实发薪资", "基本工资 vs 年终绩效奖金", "时薪制 vs 月薪制", "外企工资 vs 德企工资"], "correctIndex": 0, "explanation": "Brutto（毛收入/税前）；Netto（净收入/税后实得）。德国社保和个税从 Brutto 中扣除后为 Netto。"},
        {"id": "B1_L03_Q8", "type": "GRAMMAR_FILL", "question": "复数被动态过去时：'Alle Rechnungen _____ gestern bezahlt.'", "options": ["wurde", "wurden", "worden", "waren"], "correctIndex": 1, "explanation": "主语 Alle Rechnungen 为复数，被动态过去时助动词变位为 wurden。"},
        {"id": "B1_L03_Q9", "type": "SENTENCE_BUILDER", "question": "求职面试礼貌提问薪资待遇：", "options": ["Wie viel Geld gibst du mir?", "Wie hoch ist das Gehalt für diese Position?", "Ich will viel verdienen.", "Geld ist mein Ziel."], "correctIndex": 1, "explanation": "'Wie hoch ist das Gehalt für diese Position?' 措辞专业、客观、得体。"},
        {"id": "B1_L03_Q10", "type": "EXAM_REAL", "question": "歌德 B1 职场书信写作（求职申请信第一句）：", "options": ["Mit großem Interesse bewerbe ich mich um die Stelle als ...", "Ich brauche einen Job.", "Stellen Sie mich ein!", "Guten Tag, geben Sie mir Arbeit."], "correctIndex": 0, "explanation": "'Mit großem Interesse bewerbe ich mich um die Stelle als ...'（我怀着极大的兴趣申请贵司……一职）是正式德国求职申请书 (Anschreiben) 标准第一金句。"}
    ],
    "B1_L04": [
        {"id": "B1_L04_Q1", "type": "GRAMMAR_FILL", "question": "第二格 (Genitiv) 介词 wegen 填空：'_____ des starken Regens fand das Konzert nicht statt.'", "options": ["Wegen", "Trotz", "Während", "Statt"], "correctIndex": 0, "explanation": "wegen 意为“由于、因为”，支配第二格 (des starken Regens)；与 fand nicht statt（未举行）构成合理的因果关系。"},
        {"id": "B1_L04_Q2", "type": "GRAMMAR_FILL", "question": "第二格介词 trotz 填空（转折让步）：'_____ des schlechten Wetters machten wir eine Wanderung.'", "options": ["Wegen", "Trotz", "Während", "Anstatt"], "correctIndex": 1, "explanation": "trotz 意为“尽管、虽然”，支配第二格 (des schlechten Wetters)，后接转折结果“我们依然去徒步了”。"},
        {"id": "B1_L04_Q3", "type": "GRAMMAR_FILL", "question": "时间第二格介词 während 填空：'_____ der Sommerferien reiste er durch ganz Europa.'", "options": ["Während", "Seit", "Bis", "Vor"], "correctIndex": 0, "explanation": "während 作介词支配第二格，表示“在……期间”：während der Sommerferien (der 为阴性复数 Genitiv)。"},
        {"id": "B1_L04_Q4", "type": "GRAMMAR_FILL", "question": "第二格介词 statt / anstatt 填空：'_____ eines neuen Autos kaufte er sich ein gebrauchtes Fahrrad.'", "options": ["Wegen", "Statt", "Trotz", "Während"], "correctIndex": 1, "explanation": "statt / anstelle 意为“代替、而不是”，支配第二格：Statt eines neuen Autos。"},
        {"id": "B1_L04_Q5", "type": "GRAMMAR_FILL", "question": "阳性名词在第二格中的名词词尾变化：'wegen _____ Unfalls' (der Unfall)", "options": ["des / -es", "dem / -en", "der / -s", "den / -es"], "correctIndex": 0, "explanation": "阳性及中性名词在第二格中，定冠词变 des，名词词尾必须加 -(e)s：des Unfalles / Unfalls。"},
        {"id": "B1_L04_Q6", "type": "VOCAB_MEANING", "question": "德国租房法律术语：'die Kündigungsfrist' 意思是：", "options": ["房租减免申请期限", "解约通知期（退租提前通知法定期限，通常为3个月）", "滞纳金计算天数", "房屋维修保修期"], "correctIndex": 1, "explanation": "die Kündigungsfrist 指终止合同的法定通知预留期。租客提前解约通常须提前 3 个月书面通知房东。"},
        {"id": "B1_L04_Q7", "type": "ARTICLE", "question": "名词 'Mietvertrag' (租赁合同) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "der Vertrag 结尾，故为阳性：der Mietvertrag。"},
        {"id": "B1_L04_Q8", "type": "VOCAB_MEANING", "question": "居住生活公德：'die Ruhezeit' 在德国通常指什么时间段？", "options": ["工作日下午 2 点到 4 点", "工作日晚上 22 点到次日早晨 6 点及周日全天必须保持安静", "每年圣诞节放假", "仅限节假日凌晨"], "correctIndex": 1, "explanation": "Die gesetzliche Nachtruhe 规定从 22 点至早晨 6 点，以及周日/节假日全天，不得发出过大噪音扰邻（Ruhestörung 会被邻居报警投诉）。"},
        {"id": "B1_L04_Q9", "type": "SENTENCE_BUILDER", "question": "第二格阴性名词词尾规律：'trotz _____ schweren Krankheit' (die Krankheit)", "options": ["der", "des", "den", "dem"], "correctIndex": 0, "explanation": "阴性名词在第二格冠词变 der，但阴性名词词尾【不加】-(e)s：trotz der schweren Krankheit。"},
        {"id": "B1_L04_Q10", "type": "EXAM_REAL", "question": "歌德 B1 租房维权写信：因暖气损坏要求减租的正式用语是：", "options": ["Ich zahle gar nichts mehr.", "Ich fordere eine angemessene Mietminderung wegen Heizungsausfalls.", "Ihre Heizung ist kaputt, reparieren sofort!", "Ich hasse diese Wohnung."], "correctIndex": 1, "explanation": "'Ich fordere eine angemessene Mietminderung wegen ...'（因暖气故障要求合理减免房租）是基于德国租房法的正式书信表达。"}
    ],
    "B1_L05": [
        {"id": "B1_L05_Q1", "type": "GRAMMAR_FILL", "question": "第二虚拟式过去时 (Konjunktiv II Vergangenheit) 构成公式：", "options": ["hätte / wäre + Partizip II", "würde + Infinitiv", "hatte / war + Partizip II", "werde + Partizip II"], "correctIndex": 0, "explanation": "第二虚拟式过去时的构成公式为：hätte 或 wäre (人称变位) + 第二分词 (Partizip II) 置于句末。表示对过去的虚拟、遗憾或后悔。"},
        {"id": "B1_L05_Q2", "type": "GRAMMAR_FILL", "question": "第二虚拟式过去时（位移动词用 wäre）：'Wenn ich den Zug nicht verpasst _____, _____ ich rechtzeitig in Frankfurt gewesen.'", "options": ["hätte / wäre", "hätte / hätte", "wäre / wäre", "war / bin"], "correctIndex": 0, "explanation": "verpassen 用 hätte (hätte nicht verpasst)；sein 构成的状态/位移用 wäre (wäre gewesen)。"},
        {"id": "B1_L05_Q3", "type": "GRAMMAR_FILL", "question": "表达对过去的后悔与惋惜：'Ach, _____ ich doch damals mehr gelernt!'", "options": ["habe", "hätte", "hatte", "würde"], "correctIndex": 1, "explanation": "Hätte ich doch ... gelernt! 引导无连词非现实愿望句（变位动词居首），意为“哎，要是我当年多学一点该有多好啊！”。"},
        {"id": "B1_L05_Q4", "type": "VOCAB_MEANING", "question": "跨文化交际核心概念：'der Kulturschock' 表现为：", "options": ["对异国美食的过敏", "初到异国文化环境时因价值观和生活方式差异引发的心理不适与迷茫", "交通违章罚款", "语言考试挂科"], "correctIndex": 1, "explanation": "der Kulturschock（文化休克/文化冲击）指身处全新文化环境初期经历的心理焦虑、困惑与调适过程。"},
        {"id": "B1_L05_Q5", "type": "ARTICLE", "question": "名词 'Verhalten' (举止行为) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "由动词不定式直接转化而来的名词一律为中性：das Verhalten。"},
        {"id": "B1_L05_Q6", "type": "GRAMMAR_FILL", "question": "第二虚拟式情态动词过去时：'Ich _____ dich anrufen _____, aber mein Akku war leer.' (können)", "options": ["hätte / können", "hätte / gekonnt", "konnte / haben", "wäre / gekonnt"], "correctIndex": 0, "explanation": "情态动词双不定式规则：情态动词第二虚拟式过去时必须使用 hätte + 不定式 + 情态动词原形（Ersatzinfinitiv）：hätte anrufen können！"},
        {"id": "B1_L05_Q7", "type": "VOCAB_MEANING", "question": "跨文化交际形容词：'aufgeschlossen / vorurteilsfrei' 的含义是：", "options": ["保守闭塞的 / 充满偏见的", "思想开明的 / 不带成见偏见的", "内向孤僻的 / 自大的", "粗鲁无礼的 / 傲慢的"], "correctIndex": 1, "explanation": "aufgeschlossen 意为开明豁达的、乐于接纳新事物的；vorurteilsfrei 意为无偏见成见的。"},
        {"id": "B1_L05_Q8", "type": "SENTENCE_BUILDER", "question": "第二虚拟式过去时主从句语序：", "options": ["Wenn ich Geld gehabt hätte, hätte ich die Weltreise gemacht.", "Wenn ich hätte Geld gehabt, ich hätte gemacht die Weltreise.", "Hätte ich Geld gehabt, wenn ich die Weltreise gemacht hätte.", "Wenn Geld ich gehabt, hätte gemacht Weltreise."], "correctIndex": 0, "explanation": "从句 Wenn ... gehabt hätte（动词在句末），主句倒装 hätte ich ... gemacht。"},
        {"id": "B1_L05_Q9", "type": "GRAMMAR_FILL", "question": "虚拟语气连词 als ob 句式（仿佛……似的）：'Er tut so, als ob er von nichts gewusst _____.'", "options": ["hätte", "hatte", "habe", "hast"], "correctIndex": 0, "explanation": "als ob 引导非现实比较从句，强制使用第二虚拟式，动词 hätte 置于从句末尾。"},
        {"id": "B1_L05_Q10", "type": "EXAM_REAL", "question": "歌德 B1 探讨跨文化交流话题时的地道论述：", "options": ["Man sollte andere Bräuche respektieren und offen für Neues sein.", "Alle Menschen müssen deutsch sprechen.", "Kultur ist unwichtig.", "Ich bleibe nur zu Hause."], "correctIndex": 0, "explanation": "'Man sollte andere Bräuche respektieren und offen für Neues sein'（应当尊重异国习俗并以包容开放态度面对新事物）是标准 B1 论辩亮点句。"}
    ],
    "B1_L06": [
        {"id": "B1_L06_Q1", "type": "GRAMMAR_FILL", "question": "目的状语选择（主语一致时用 um...zu，主语不一致时用 damit）：'Ich lerne Deutsch, _____ ich in Deutschland studieren kann.'", "options": ["um zu", "damit", "weil", "obwohl"], "correctIndex": 1, "explanation": "当主从句主语相同且从句保留人称代词和主语时，可用 damit 或 um...zu；但此处从句明确含有 ich 与 can，故必须用引导连词 damit！"},
        {"id": "B1_L06_Q2", "type": "GRAMMAR_FILL", "question": "目的状语选择（主语不一致时）：'Die Eltern arbeiten viel, _____ ihre Kinder eine gute Bildung bekommen.'", "options": ["um zu", "damit", "weil", "denn"], "correctIndex": 1, "explanation": "主句主语是 Die Eltern，从句主语是 ihre Kinder，主语不同时【绝对不能】用 um...zu，强制只能使用 damit！"},
        {"id": "B1_L06_Q3", "type": "GRAMMAR_FILL", "question": "um...zu 句式结构：'Er treibt täglich Sport, _____ gesund _____.' (bleiben)", "options": ["um / zu bleiben", "damit / bleibt", "um / geblieben", "zu / bleiben"], "correctIndex": 0, "explanation": "um + 宾语/状语 + zu + 动词原形：um gesund zu bleiben（为了保持健康）。主语前后一致 (Er)。"},
        {"id": "B1_L06_Q4", "type": "VOCAB_MEANING", "question": "预防医学核心词：'die Vorsorgeuntersuchung' 意思是：", "options": ["急诊抢救", "定期健康体检 / 预防性筛查", "手术知情同意书", "买药发票"], "correctIndex": 1, "explanation": "die Vorsorge（预防保健）+ die Untersuchung（检查）= 预防性健康体检。"},
        {"id": "B1_L06_Q5", "type": "ARTICLE", "question": "名词 'Ernährung' (日常饮食、营养膳食) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "-ung 结尾必为阴性名词：die Ernährung。"},
        {"id": "B1_L06_Q6", "type": "GRAMMAR_FILL", "question": "um...zu 遇到可分动词时的拼写规则：'Ich stehe früh auf, _____ den Sonnenaufgang _____.' (ansehen)", "options": ["um / anzusehen", "um / zu ansehen", "damit / ansehen", "um / ansehen zu"], "correctIndex": 0, "explanation": "可分动词在 um...zu 中，zu 必须嵌入前缀与词根之间：anzusehen。"},
        {"id": "B1_L06_Q7", "type": "VOCAB_MEANING", "question": "营养学核心概念：'ausgewogene Ernährung' 含义是：", "options": ["极端的节食减肥", "均衡合理的膳食营养搭配", "高热量油炸食品", "纯素食主义"], "correctIndex": 1, "explanation": "ausgewogen 意为均衡平衡的；ausgewogene Ernährung 即营养均衡的饮食结构。"},
        {"id": "B1_L06_Q8", "type": "SENTENCE_BUILDER", "question": "选出语序完全正确的 damit 目的从句：", "options": ["Er spricht langsam, damit ihn alle verstehen können.", "Er spricht langsam, damit können ihn alle verstehen.", "Er spricht langsam, um ihn alle zu verstehen.", "Er spricht langsam, damit ihn alle zu verstehen."], "correctIndex": 0, "explanation": "damit 从句中，变位动词（或情态动词 können）必须位于从句末尾：... damit ihn alle verstehen können。"},
        {"id": "B1_L06_Q9", "type": "GRAMMAR_FILL", "question": "固定动词介词搭配：'leiden ____ einer schweren Allergie' (遭受某种疾病折磨)", "options": ["an", "unter", "über", "von"], "correctIndex": 0, "explanation": "leiden an + Dativ 专指患有某种具体生理疾病 (an einer Allergie / an Krebs leiden)；leiden unter + Dativ 侧重承受外界恶劣条件或精神压力 (unter Stress / Lärm leiden)。"},
        {"id": "B1_L06_Q10", "type": "EXAM_REAL", "question": "歌德 B1 口语表达健康建议：", "options": ["Es ist ratsam, sich regelmäßig zu bewegen und Stress abzubauen.", "Essen Sie nur Pommes.", "Arztbesuche sind Zeitverschwendung.", "Schlafen ist ungesund."], "correctIndex": 0, "explanation": "'Es ist ratsam, ... zu + Infinitiv'（建议/理智的做法是……）是提供健康养生建议的高分句式。"}
    ],
    "B1_L07": [
        {"id": "B1_L07_Q1", "type": "GRAMMAR_FILL", "question": "代副词 (Pronominaladverb) 构造规律：指代事物时的 da(r)- + 介词：'Wartest du auf den Bus? - Ja, ich warte _____.'", "options": ["auf ihn", "darauf", "worauf", "daran"], "correctIndex": 1, "explanation": "指代无生命的事物或概念（der Bus）时，必须使用代副词 darauf (da + r + auf)；只有指代具体的人时才用介词+代词 (auf ihn)。"},
        {"id": "B1_L07_Q2", "type": "GRAMMAR_FILL", "question": "疑问代副词 wo(r)- + 介词填空（提问事物）：'_____ interessierst du dich?' - 'Für moderne Technologie.'", "options": ["Wofür", "Für wen", "Worüber", "Dafür"], "correctIndex": 0, "explanation": "提问非人事物用 wo(r)- + 介词：sich interessieren für 对应 Wofür?（针对人则为 Für wen?）。"},
        {"id": "B1_L07_Q3", "type": "GRAMMAR_FILL", "question": "提问人 vs 提问事物辨析：'_____ denkst du?' - 'An meine Freundin in München.'", "options": ["Woran", "An wen", "Worüber", "Über wen"], "correctIndex": 1, "explanation": "回答是具体的人 (meine Freundin)，介词 an + Akkusativ 提问人强制使用 'An wen?'（若是事物才用 Woran?）。"},
        {"id": "B1_L07_Q4", "type": "VOCAB_MEANING", "question": "欧洲数字合规核心法规：'die DSGVO' (Datenschutz-Grundverordnung) 是指：", "options": ["电子电气废弃物指令", "通用数据保护条例（欧盟个人隐私与数据保护法）", "跨境电商反垄断法", "人工智能版权法"], "correctIndex": 1, "explanation": "die DSGVO（通用数据保护条例）是欧盟具有里程碑意义的数据安全与个人隐私保护法规。"},
        {"id": "B1_L07_Q5", "type": "ARTICLE", "question": "名词 'Passwortsicherheit' (密码安全性) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "-heit 结尾必为阴性名词：die Sicherheit, die Passwortsicherheit。"},
        {"id": "B1_L07_Q6", "type": "GRAMMAR_FILL", "question": "动词 achten 的介词搭配与代副词：'Achten Sie bitte _____!' (auf + das Kleingedruckte)", "options": ["darauf", "daran", "dazu", "damit"], "correctIndex": 0, "explanation": "achten auf + Akkusativ（注意某事），指代该事物使用 darauf：Achten Sie bitte darauf!。"},
        {"id": "B1_L07_Q7", "type": "VOCAB_MEANING", "question": "网络安全威胁术语：'der Cyberangriff / Phishing' 意思是：", "options": ["云端备份 / 数据加密", "网络黑客攻击 / 网络钓鱼欺诈", "软件升级 / 杀毒扫描", "宽带提速 / 光纤入户"], "correctIndex": 1, "explanation": "der Cyberangriff 指网络攻击，Phishing（网络钓鱼）通过伪造网页邮件骗取用户密码及银行卡信息。"},
        {"id": "B1_L07_Q8", "type": "SENTENCE_BUILDER", "question": "代副词引出 dass 从句：'Er träumt davon, _____.' (dass / er / ein Buch / schreibt)", "options": ["dass er ein Buch schreibt", "dass er schreibt ein Buch", "er ein Buch schreibt dass", "schreibt dass er ein Buch"], "correctIndex": 0, "explanation": "träumen von 引出 davon，后续衔接 dass 从句，动词 schreibt 置于从句末尾。"},
        {"id": "B1_L07_Q9", "type": "GRAMMAR_FILL", "question": "元音介词前字母 -r- 的插入原则：da + auf 构成 _____，wo + an 构成 _____：", "options": ["daauf / woan", "darauf / woran", "drauf / dran", "daraus / woraus"], "correctIndex": 1, "explanation": "当介词以元音字母 (a, e, i, o, u) 开头时，da 和 wo 必须插入字母 -r- 辅助连读：darauf, daran, woran, worüber。"},
        {"id": "B1_L07_Q10", "type": "EXAM_REAL", "question": "歌德 B1 书面议论文：谈论社交网络利弊的高分总结句：", "options": ["Soziale Medien bieten viele Vorteile, bergen aber auch Risiken für den Datenschutz.", "Das Internet ist total schlecht.", "Alle Menschen müssen ihr Handy wegwerfen.", "Ich mag keine Computer."], "correctIndex": 0, "explanation": "'... bieten viele Vorteile, bergen aber auch Risiken für ...'（提供了诸多益处，但也潜藏着……的风险）是典型的辩证思辨句式。"}
    ],
    "B1_L08": [
        {"id": "B1_L08_Q1", "type": "GRAMMAR_FILL", "question": "被动替代形式 (Passiversatz)：'sein + zu + Infinitiv' 表示必要性或可能性：'Diese Aufgabe ist bis morgen zu erledigen.' 含义等同于：", "options": ["kann erledigt werden", "muss erledigt werden", "darf nicht erledigt werden", "wird freiwillig erledigt"], "correctIndex": 1, "explanation": "sein + zu + Infinitiv 带有情态动词 müssen（必须）或 können（可以）的被动含义。在时间期限限制下，'ist zu erledigen' 等同于 'muss erledigt werden'。"},
        {"id": "B1_L08_Q2", "type": "GRAMMAR_FILL", "question": "被动替代形式（表示可能性 können）：'Das Problem ist leicht zu lösen.' 等同于：", "options": ["Das Problem muss gelöst werden.", "Das Problem kann leicht gelöst werden.", "Das Problem soll nicht gelöst werden.", "Niemand löst das Problem."], "correctIndex": 1, "explanation": "带有 leicht / schwer / einfach 等评价性副词时，sein + zu + Infinitiv 表达可能性 (kann gelöst werden)。"},
        {"id": "B1_L08_Q3", "type": "VOCAB_MEANING", "question": "环保与能源革命核心词：'erneuerbare Energien' 包含：", "options": ["煤炭、石油、天然气", "风能、太阳能、水能与地热能", "柴油、汽油、核燃料", "重油与塑料燃烧"], "correctIndex": 1, "explanation": "erneuerbare Energien 即可再生能源（绿色能源），如 Windkraft, Solarenergie, Wasserkraft。"},
        {"id": "B1_L08_Q4", "type": "ARTICLE", "question": "名词 'Nachhaltigkeit' (可持续性、生态永续) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "-keit 结尾必为阴性名词：die Nachhaltigkeit。"},
        {"id": "B1_L08_Q5", "type": "GRAMMAR_FILL", "question": "形容词后置词尾 -bar 构成的被动替代形态：'Das Wasser ist nicht trinkbar.' 意思是：", "options": ["Das Wasser muss getrunken werden.", "Das Wasser kann nicht getrunken werden.", "Das Wasser wird getrunken.", "Niemand trinkt Wasser."], "correctIndex": 1, "explanation": "形容词词缀 -bar 表示“可……的”，trinkbar = kann getrunken werden，加上 nicht 即“不能饮用”。"},
        {"id": "B1_L08_Q6", "type": "VOCAB_MEANING", "question": "温室效应科学概念：'der Treibhauseffekt / CO2-Ausstoß' 意思是：", "options": ["臭氧层修复 / 氧气制造", "温室效应 / 二氧化碳排放量", "酸雨沉降 / 沙尘暴", "土地荒漠化 / 冰川扩张"], "correctIndex": 1, "explanation": "der Treibhauseffekt 是温室效应；der CO2-Ausstoß 指碳排放量。"},
        {"id": "B1_L08_Q7", "type": "GRAMMAR_FILL", "question": "动词 beitragen 的介词搭配：'Jeder Bürger kann zum Umweltschutz _____.'", "options": ["beitragen", "beiträgt", "beizutragen", "beigetragen"], "correctIndex": 0, "explanation": "固定搭配：beitragen zu + Dativ（为……做出贡献）。情态动词 kann 后接动词原形 beitragen。"},
        {"id": "B1_L08_Q8", "type": "SENTENCE_BUILDER", "question": "将 sein + zu 不定式构成完整被动替代句：'Der Müll / sofort / trennen (sein + zu)'", "options": ["Der Müll ist sofort zu trennen.", "Der Müll trennt sofort zu sein.", "Zu trennen ist sofort der Müll.", "Der Müll sein zu sofort getrennt."], "correctIndex": 0, "explanation": "主语 Der Müll + 助动词 ist + 状语 sofort + 不定式 zu trennen。"},
        {"id": "B1_L08_Q9", "type": "VOCAB_MEANING", "question": "环保行动动词：'Energie sparen' 与 'Ressourcen schonen' 含义是：", "options": ["浪费能源与过度开采", "节约能源与珍惜保护资源", "购买更多家电", "提高电价收费"], "correctIndex": 1, "explanation": "Energie sparen 意为节约能源；Ressourcen schonen 意为保护/节约自然资源。"},
        {"id": "B1_L08_Q10", "type": "EXAM_REAL", "question": "歌德 B1 环保演说号召句：", "options": ["Wir müssen jetzt handeln, um unseren Planeten für zukünftige Generationen zu bewahren.", "Klimawandel existiert nicht.", "Es ist mir egal, was mit der Umwelt passiert.", "Fabriken dürfen mehr Rauch machen."], "correctIndex": 0, "explanation": "'Wir müssen jetzt handeln, um unseren Planeten für zukünftige Generationen zu bewahren' 是环保类大作文高分收尾金句。"}
    ],
    "B1_L09": [
        {"id": "B1_L09_Q1", "type": "GRAMMAR_FILL", "question": "第一分词 (Partizip I) 构成规则：动词原形 + -d：动词 singen 的第一分词是：", "options": ["gesungen", "singend", "singt", "singte"], "correctIndex": 1, "explanation": "第一分词 (Partizip I) 构成规则为：动词原形 + d (singen -> singend, schlafen -> schlafend)，表示正在进行的主动动作。"},
        {"id": "B1_L09_Q2", "type": "GRAMMAR_FILL", "question": "第一分词作形容词定语并加格词尾：'Das _____ Kind lacht laut.' (spielen, 中性 das Kind)", "options": ["spielte", "gespielte", "spielende", "spielenden"], "correctIndex": 2, "explanation": "第一分词 spielend 作定语修饰中性名词 das Kind，定冠词后第一格词尾加 -e：das spielende Kind（正在玩耍的孩子）。"},
        {"id": "B1_L09_Q3", "type": "GRAMMAR_FILL", "question": "第二分词 (Partizip II) 作定语修饰被动完成状态：'Das gestern _____ Buch war sehr spannend.' (lesen, 中性 das Buch)", "options": ["lesende", "gelesene", "gelesenes", "gelesenen"], "correctIndex": 1, "explanation": "第二分词 gelesene 表示已经完成的被动状态（被读过的书），定冠词中性第一格加 -e：das gelesene Buch。"},
        {"id": "B1_L09_Q4", "type": "VOCAB_MEANING", "question": "德国公民社会支柱：'das Ehrenamt' 指的是：", "options": ["高薪企业高管职位", "无薪酬自愿从事的公益志愿服务 / 义工", "公务员终身编制", "军校荣誉学员"], "correctIndex": 1, "explanation": "das Ehrenamt（名誉职务/志愿者服务）在德国极为普及，数千万德国人在消防队、体育俱乐部、难民救助中义务奉献。"},
        {"id": "B1_L09_Q5", "type": "ARTICLE", "question": "名词 'Gesellschaft' (社会、协会组织) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "-schaft 结尾必为阴性名词：die Gesellschaft。"},
        {"id": "B1_L09_Q6", "type": "GRAMMAR_FILL", "question": "第一分词与第二分词含义辨析：'die steigenden Preise' vs 'die gestiegenen Preise'：", "options": ["正在上涨的物价（进行中） vs 已经上涨后的物价（完成状态）", "下降的物价 vs 上涨的物价", "固定的物价 vs 浮动的物价", "两词毫无区别"], "correctIndex": 0, "explanation": "Partizip I (steigend) 表示正在持续上升的主动过程；Partizip II (gestiegen) 表示已经完成上涨后的状态。"},
        {"id": "B1_L09_Q7", "type": "VOCAB_MEANING", "question": "动词短语搭配：'sich engagieren für + Akkusativ' 意思是：", "options": ["反对批判某事", "积极投身于 / 致力于某项事业", "放弃参与某事", "对某事冷眼旁观"], "correctIndex": 1, "explanation": "sich engagieren für 意为积极致力于（如 sich für Menschenrechte / den Tierschutz engagieren）。"},
        {"id": "B1_L09_Q8", "type": "SENTENCE_BUILDER", "question": "第一分词副词用法（表示伴随动作）：'Er verließ _____ das Zimmer.' (weinen)", "options": ["weinend", "geweint", "weinte", "zu weinen"], "correctIndex": 0, "explanation": "第一分词作状语时不加任何词尾，修饰伴随状态：Er verließ weinend das Zimmer（他哭着离开了房间）。"},
        {"id": "B1_L09_Q9", "type": "GRAMMAR_FILL", "question": "及物动词第二分词作定语的被动含义：'die reparierte Uhr' 还原为从句是：", "options": ["die Uhr, die repariert", "die Uhr, die repariert worden ist", "die Uhr, die reparieren will", "die Uhr, die repariert wird haben"], "correctIndex": 1, "explanation": "及物动词第二分词定语具备被动完成时含义：die Uhr, die repariert worden ist（被修理好的钟表）。"},
        {"id": "B1_L09_Q10", "type": "EXAM_REAL", "question": "歌德 B1 讨论志愿者活动价值的经典表述：", "options": ["Freiwilligenarbeit stärkt den gesellschaftlichen Zusammenhalt.", "Freiwilligenarbeit ist reine Zeitverschwendung.", "Man sollte nur für viel Geld arbeiten.", "Niemand hilft anderen freiwillig."], "correctIndex": 0, "explanation": "'Freiwilligenarbeit stärkt den gesellschaftlichen Zusammenhalt'（志愿服务增强了社会的凝聚力）是高分学术论述句。"}
    ],
    "B1_L10": [
        {"id": "B1_L10_Q1", "type": "GRAMMAR_FILL", "question": "无人称被动态 (Unpersönliches Passiv) 构成：不及物动词被动句首用代词 es 占位：'_____ wird hier nicht geraucht!'", "options": ["Es", "Er", "Man", "Das"], "correctIndex": 0, "explanation": "当不及物动词变为被动态且句首无其他成分时，必须用虚词 Es 占据第 1 位：Es wird hier nicht geraucht!。"},
        {"id": "B1_L10_Q2", "type": "GRAMMAR_FILL", "question": "无人称被动态中，当其他状语占第 1 位时，虚词 es 必须脱落：'Hier _____ heute viel getanzt.'", "options": ["es wird", "wird", "wurde es", "worden"], "correctIndex": 1, "explanation": "虚词 es 只是句首占位符！一旦其他状语（如 Hier）占据第 1 位，es 必须彻底脱落消失：Hier wird heute viel getanzt（而非 *Hier wird es...）。"},
        {"id": "B1_L10_Q3", "type": "GRAMMAR_FILL", "question": "支配第三格动词转被动态时，第三格宾语形态保持不变：'Der Arzt hilft dem Patienten.' -> 'Dem Patienten _____ vom Arzt geholfen.'", "options": ["wird", "werden", "ist", "hat"], "correctIndex": 0, "explanation": "纯第三格动词转被动时，第三格名词不变，动词强制保持第三人称单数形式 wird：Dem Patienten wird geholfen！"},
        {"id": "B1_L10_Q4", "type": "VOCAB_MEANING", "question": "现代消费心理学词汇：'der Spontankauf / Impulskauf' 意思是：", "options": ["理性比价购买", "冲动消费 / 毫无预谋的即兴购买", "定期批量采购", "退货维权"], "correctIndex": 1, "explanation": "Spontankauf 或 Impulskauf 指消费者在商场或直播间没有事先计划而临时起意冲动购买。"},
        {"id": "B1_L10_Q5", "type": "ARTICLE", "question": "名词 'Konto' (银行账户) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "das Konto (Pl. die Konten)，如 ein Girokonto eröffnen（开立活期账户）。"},
        {"id": "B1_L10_Q6", "type": "VOCAB_MEANING", "question": "个人财务管理术语：'Schulden abbauen' 意思是：", "options": ["增加信用卡额度", "偿还消除债务", "投资高风险股票", "办理房屋贷款"], "correctIndex": 1, "explanation": "die Schulden（债务）；Schulden abbauen 意为逐步还清并减少债务。"},
        {"id": "B1_L10_Q7", "type": "GRAMMAR_FILL", "question": "动词 ausgeben 的介词搭配：'Er gibt zu viel Geld _____ Kleidung aus.'", "options": ["für", "an", "über", "in"], "correctIndex": 0, "explanation": "固定搭配：Geld ausgeben für + Akkusativ（在某事物上花钱）。"},
        {"id": "B1_L10_Q8", "type": "SENTENCE_BUILDER", "question": "无人称被动语序排列：'Am Wochenende / in der Fabrik / arbeiten (被动 Präsens)'", "options": ["Am Wochenende wird in der Fabrik nicht gearbeitet.", "Am Wochenende es wird gearbeitet nicht.", "Es am Wochenende gearbeitet wird in der Fabrik.", "In der Fabrik am Wochenende gearbeitet es wird."], "correctIndex": 0, "explanation": "时间状语 Am Wochenende 占第 1 位，变位动词 wird 占第 2 位，分词 gearbeitet 置于句末，无虚词 es。"},
        {"id": "B1_L10_Q9", "type": "VOCAB_MEANING", "question": "理财观念形容词：'sparsam' vs 'geizig' 的褒贬色彩区别是：", "options": ["节俭理智的（褒义） vs 吝啬铁公鸡的（贬义）", "挥霍的 vs 贫困的", "富有的 vs 贪婪的", "两词色彩完全相同"], "correctIndex": 0, "explanation": "sparsam 指懂节俭、不铺张浪费（褒义）；geizig 指过度小气、舍不得花一分钱（贬义）。"},
        {"id": "B1_L10_Q10", "type": "EXAM_REAL", "question": "歌德 B1 探讨消费主义与网购的思辨句：", "options": ["Online-Shopping ist zwar bequem, verleitet aber oft zu unnötigen Ausgaben.", "Kaufen macht immer arm.", "Niemand braucht ein Bankkonto.", "Geld ausgeben ist verboten."], "correctIndex": 0, "explanation": "'Online-Shopping ist zwar bequem, verleitet aber oft zu unnötigen Ausgaben'（网购虽然方便，但往往诱导人们产生不必要的开销）展示了虽然...但是...的高级思辨。"}
    ],
    "B1_L11": [
        {"id": "B1_L11_Q1", "type": "GRAMMAR_FILL", "question": "带介词的关系从句（介词位于关系代词前）：'Das ist der Mann, _____ ich gesprochen habe.' (sprechen mit + Dativ, 阳性 der Mann)", "options": ["mit dem", "mit den", "mit der", "womit"], "correctIndex": 0, "explanation": "先行词是阳性单数 der Mann，介词 mit 支配第三格，故关系代词为 dem，组合为 mit dem。"},
        {"id": "B1_L11_Q2", "type": "GRAMMAR_FILL", "question": "带介词的关系从句（中性名词第四格）：'Das Thema, _____ wir diskutieren, ist hochinteressant.' (diskutieren über + Akkusativ)", "options": ["über das", "über dem", "worüber", "über den"], "correctIndex": 0, "explanation": "先行词为中性 das Thema，介词 über 在该动词搭配中支配第四格，中性第四格定冠词为 das，故为 über das。"},
        {"id": "B1_L11_Q3", "type": "GRAMMAR_FILL", "question": "带介词的关系从句（复数第三格）：'Die Freunde, _____ ich in den Urlaub gefahren bin, kommen aus Wien.' (fahren mit + Dativ)", "options": ["mit denen", "mit die", "mit den", "mit deren"], "correctIndex": 0, "explanation": "复数第三格关系代词必须加 -en，即 denen（注意区别定冠词 den）：mit denen！"},
        {"id": "B1_L11_Q4", "type": "VOCAB_MEANING", "question": "德国文学巨擘：'Goethe' 与 'Schiller' 属于哪个辉煌文学时期？", "options": ["Sturm und Drang / Weimarer Klassik (魏玛古典主义)", "Barock (巴洛克)", "Mittelalter (中世纪)", "Expressionismus (表现主义)"], "correctIndex": 0, "explanation": "歌德 (Goethe) 与席勒 (Schiller) 在魏玛的紧密合作为德意志古典文学（Weimarer Klassik）奠定了巅峰基石。"},
        {"id": "B1_L11_Q5", "type": "ARTICLE", "question": "名词 'Theaterstück' (戏剧作品、话剧剧本) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "das Stück 结尾，复合词必为中性：das Theaterstück。"},
        {"id": "B1_L11_Q6", "type": "GRAMMAR_FILL", "question": "带介词的关系从句（阴性名词第三格）：'Die Stadt, _____ ich seit fünf Jahren lebe, gefällt mir sehr.' (leben in + Dativ)", "options": ["in der", "in die", "in dem", "wohin"], "correctIndex": 0, "explanation": "先行词为阴性 die Stadt，静止地点 in 支配第三格，阴性第三格冠词为 der，组合为 in der。"},
        {"id": "B1_L11_Q7", "type": "VOCAB_MEANING", "question": "电影与戏剧评论核心词：'die Handlung / die Besetzung' 含义分别是：", "options": ["剧情脉络 / 演员阵容", "电影院地址 / 爆米花套餐", "票房收入 / 赞助商", "服装道具 / 门票价格"], "correctIndex": 0, "explanation": "die Handlung 是故事发展情节与脉络；die Besetzung 是演员阵容与选角。"},
        {"id": "B1_L11_Q8", "type": "SENTENCE_BUILDER", "question": "排列带介词的关系从句：'Das Buch, _____ habe, ist ein Bestseller.' (aus dem / ich / vorgelesen)", "options": ["aus dem ich vorgelesen habe", "aus dem vorgelesen ich habe", "ich habe aus dem vorgelesen", "vorgelesen habe ich aus dem"], "correctIndex": 0, "explanation": "关系从句语序：关系代词短语 aus dem 置于从句首，主语 ich 紧随，助动词 habe 放在从句末尾。"},
        {"id": "B1_L11_Q9", "type": "GRAMMAR_FILL", "question": "带介词的关系从句（先行词为阳性第四格）：'Der Vorschlag, _____ ich nachgedacht habe, ist gut.' (nachdenken über + Akkusativ)", "options": ["über den", "über dem", "über der", "worüber"], "correctIndex": 0, "explanation": "先行词为阳性 der Vorschlag，nachdenken über 支配第四格，阳性第四格为 den，组合为 über den。"},
        {"id": "B1_L11_Q10", "type": "EXAM_REAL", "question": "歌德 B1 文化艺术评论（表达对艺术作品的喜爱）：", "options": ["Dieses Werk regt das Publikum zum Nachdenken an und berührt emotional.", "Das Bild ist bunt und langweilig.", "Ich verstehe nichts davon.", "Kunst sollte verboten werden."], "correctIndex": 0, "explanation": "'regt zum Nachdenken an und berührt emotional'（引人深思并带来强烈的情感共鸣）是影评书评的高级鉴赏用语。"}
    ],
    "B1_L12": [
        {"id": "B1_L12_Q1", "type": "GRAMMAR_FILL", "question": "时间从句连词 seitdem (自从...以来)：'_____ er in Hamburg wohnt, fährt er jeden Tag mit der U-Bahn.'", "options": ["Seitdem", "Bis", "Sobald", "Solange"], "correctIndex": 0, "explanation": "seitdem 表示自过去某一时间点开始，动作一直延续至今（自从……以来），从句动词 wohnt 在句尾。"},
        {"id": "B1_L12_Q2", "type": "GRAMMAR_FILL", "question": "时间从句连词 bis (直到...为止)：'Wir müssen warten, _____ der Zug kommt.'", "options": ["seitdem", "bis", "sobald", "nachdem"], "correctIndex": 1, "explanation": "bis 引导时间从句表示终点，意为“直到……为止”。"},
        {"id": "B1_L12_Q3", "type": "GRAMMAR_FILL", "question": "时间从句连词 sobald (一...就...)：'_____ die Ampel grün wird, fährt das Auto los.'", "options": ["Sobald", "Solange", "Seit", "Während"], "correctIndex": 0, "explanation": "sobald 表示紧随某动作发生之后的即时动作，意为“一……就…… / 一旦……”。"},
        {"id": "B1_L12_Q4", "type": "GRAMMAR_FILL", "question": "时间从句连词 solange (只要...期间)：'_____ der Akku hält, können wir mit dem E-Bike fahren.'", "options": ["Sobald", "Solange", "Bis", "Nachdem"], "correctIndex": 1, "explanation": "solange 表示两件事在时间跨度上平行持续，意为“只要……在……期间”。"},
        {"id": "B1_L12_Q5", "type": "VOCAB_MEANING", "question": "德国交通出行变革核心词：'die Verkehrswende' 核心主旨是：", "options": ["全面扩建高速公路", "从以私家燃油车为中心转向公共交通、自行车与低碳出行体系", "禁止所有市民出行", "取消全部铁路客运"], "correctIndex": 1, "explanation": "die Verkehrswende（交通转型）是德国现代交通战略，旨在推广电动车、轻轨与骑行基础设施，降低碳排放。"},
        {"id": "B1_L12_Q6", "type": "ARTICLE", "question": "名词 'Deutschlandticket' (德国全境49欧公共交通通票) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "das Ticket 结尾，复合词必定为中性：das Deutschlandticket。"},
        {"id": "B1_L12_Q7", "type": "VOCAB_MEANING", "question": "共享出行新兴形态：'das Carsharing' 属于什么模式？", "options": ["买断私家车", "汽车分时共享租赁平台", "长途大巴拼车", "无证黑车"], "correctIndex": 1, "explanation": "Carsharing（汽车共享）用户通过手机 App 随借随还汽车，无需自己买车保养。"},
        {"id": "B1_L12_Q8", "type": "SENTENCE_BUILDER", "question": "选出语序完全正确的时间复合句：", "options": ["Sobald der Regen aufhört, gehen wir nach draußen.", "Sobald hört der Regen auf, wir gehen nach draußen.", "Sobald der Regen aufhört gehen wir nach draußen.", "Wir gehen nach draußen sobald hört der Regen auf."], "correctIndex": 0, "explanation": "从句 Sobald der Regen aufhört，主句紧接着倒装 gehen wir nach draußen。"},
        {"id": "B1_L12_Q9", "type": "GRAMMAR_FILL", "question": "时态前后呼应：nachdem 引导的从句若主句为现在时，nachdem 从句须使用：'Nachdem er gefrühstückt _____, geht er zur Arbeit.'", "options": ["hat", "hatte", "wird", "habe"], "correctIndex": 0, "explanation": "时态呼应铁律：主句现在时 (geht)，nachdem 从句先于其发生，必须用现在完成时 (gefrühstückt hat)！若主句为过去时 (ging)，从句才用过去完成时 (hatte)。"},
        {"id": "B1_L12_Q10", "type": "EXAM_REAL", "question": "歌德 B1 探讨低碳交通出行的典型倡议：", "options": ["Der Ausbau des öffentlichen Nahverkehrs ist unverzichtbar für eine lebenswerte Stadt.", "Alle Züge sollten abgeschafft werden.", "Fahrradfahren ist gefährlich und sinnlos.", "Man sollte nur Autos kaufen."], "correctIndex": 0, "explanation": "'Der Ausbau des öffentlichen Nahverkehrs ist unverzichtbar für ...'（扩建城市公共短途交通对于宜居城市而言不可或缺）是规范有力的学术倡议句。"}
    ],
    "B1_L13": [
        {"id": "B1_L13_Q1", "type": "GRAMMAR_FILL", "question": "第一虚拟式 (Konjunktiv I) 动词 sein 的特殊变位（第三人称单数）：'Der Arzt sagte, der Patient _____ wieder gesund.'", "options": ["ist", "sei", "wäre", "seien"], "correctIndex": 1, "explanation": "第一虚拟式中，动词 sein 的单数第一/第三人称为 sei（er sei gesund）。用于转述医生所言的间接引语。"},
        {"id": "B1_L13_Q2", "type": "GRAMMAR_FILL", "question": "第一虚拟式动词 haben（第三人称单数）：'Sie behauptet, sie _____ keine Zeit.'", "options": ["habe", "hätte", "hat", "haben"], "correctIndex": 0, "explanation": "haben 的第一虚拟式第三人称单数形式为 habe（词干 hab- + -e）。"},
        {"id": "B1_L13_Q3", "type": "GRAMMAR_FILL", "question": "当第一虚拟式与直陈式现在时同形时，间接引语必须用第二虚拟式替代：'Die Zeugen sagen, sie _____ den Unfall gesehen.'", "options": ["haben", "hätten", "seien", "wurden"], "correctIndex": 1, "explanation": "主语为 sie (复数)，第一虚拟式 haben 与直陈式同形，为避免歧义，强制使用第二虚拟式 hätten 作为替身形式！"},
        {"id": "B1_L13_Q4", "type": "VOCAB_MEANING", "question": "现代心理学高频词：'das Burnout-Syndrom' 表现为：", "options": ["肌肉急性拉伤", "长期工作高压导致的身体与心理极度耗竭崩溃综合征", "暴饮暴食", "社交恐惧症"], "correctIndex": 1, "explanation": "Burnout（职业倦怠/耗竭综合征）指在长期工作过载压力下产生的心力交瘁、职业成就感丧失的状态。"},
        {"id": "B1_L13_Q5", "type": "ARTICLE", "question": "名词 'Selbstbewusstsein' (自信心、自我意识) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "das Bewusstsein（意识）结尾，故为中性：das Selbstbewusstsein。"},
        {"id": "B1_L13_Q6", "type": "GRAMMAR_FILL", "question": "第一虚拟式情态动词 wollen（第三人称单数）：'Er sagte, er _____ morgen abreisen.'", "options": ["wolle", "wollte", "will", "wollen"], "correctIndex": 0, "explanation": "wollen 的第一虚拟式第三人称单数形式为 wolle。"},
        {"id": "B1_L13_Q7", "type": "VOCAB_MEANING", "question": "情绪调节动词短语：'Stress abbauen' 意思是：", "options": ["制造巨大压力", "缓解宣泄与减轻心理压力", "忽视情绪问题", "产生焦虑情绪"], "correctIndex": 1, "explanation": "Stress abbauen 是心理学与健康中最常用的短语，意为缓解、排解工作和生活压力。"},
        {"id": "B1_L13_Q8", "type": "SENTENCE_BUILDER", "question": "间接引语在有连词 dass 与无连词时的语序区别：", "options": ["有 dass 动词在从句末；无 dass 动词占第 2 位保持主句语序", "两者动词都必须在句首", "有 dass 动词在第 2 位", "无 dass 动词在句末"], "correctIndex": 0, "explanation": "间接引语若保留连词 dass，按从句规则动词放句末 (Er sagt, dass er krank sei)；若省略 dass，则恢复主句 V2 语序 (Er sagt, er sei krank)。"},
        {"id": "B1_L13_Q9", "type": "VOCAB_MEANING", "question": "积极心理学核心概念：'die Resilienz' 指的是：", "options": ["记忆力衰退", "心理韧性 / 面对逆境挫折的复原力", "多动症倾向", "睡眠障碍"], "correctIndex": 1, "explanation": "die Resilienz（心理抗逆力/复原力）指个体面对困难、危机时的心理承受力与自我修复能力。"},
        {"id": "B1_L13_Q10", "type": "EXAM_REAL", "question": "歌德 B1 口语表达同理心与安慰：", "options": ["Ich kann gut nachvollziehen, wie du dich in dieser schwierigen Phase fühlst.", "Selber schuld!", "Stell dich nicht so an.", "Das interessiert mich nicht."], "correctIndex": 0, "explanation": "'Ich kann gut nachvollziehen, wie du dich in dieser Phase fühlst'（我非常能够理解你在这段艰难时期的感受）是极富同理心的高级交际金句。"}
    ],
    "B1_L14": [
        {"id": "B1_L14_Q1", "type": "GRAMMAR_FILL", "question": "功能动词短语 (Funktionsverbgefüge)：'zur Verfügung stehen' 含义等同于被动/可能动词：", "options": ["benutzen können (可供使用)", "kaufen müssen", "verkaufen wollen", "verlieren"], "correctIndex": 0, "explanation": "zur Verfügung stehen 表示“可供支配/可供使用”（不及物/状态）；jemandem etwas zur Verfügung stellen 则表示“向某人提供某物”（及物/动作）。"},
        {"id": "B1_L14_Q2", "type": "GRAMMAR_FILL", "question": "功能动词短语填空：'Das neue Gesetz tritt ab dem 1. Januar in _____.' (生效)", "options": ["Kraft", "Macht", "Recht", "Wirkung"], "correctIndex": 0, "explanation": "in Kraft treten 是法律法规范畴固定功能动词短语，意为“（法律、规定）生效实施”。"},
        {"id": "B1_L14_Q3", "type": "GRAMMAR_FILL", "question": "功能动词短语填空：'eine Entscheidung _____' (做出决定)", "options": ["machen", "treffen", "tun", "bringen"], "correctIndex": 1, "explanation": "德语中“做决定”规范表达是 eine Entscheidung treffen（或 fällen），不可按英语直译为 *Entscheidung machen！"},
        {"id": "B1_L14_Q4", "type": "VOCAB_MEANING", "question": "德国现代史标志性事件：'der Mauerfall' 发生在：", "options": ["1945年5月8日", "1989年11月9日（柏林墙倒塌）", "1990年10月3日", "1961年8月13日"], "correctIndex": 1, "explanation": "1989年11月9日柏林墙倒塌 (Mauerfall)，为随后1990年10月3日的两德统一奠定了基础。"},
        {"id": "B1_L14_Q5", "type": "ARTICLE", "question": "名词 'Wiedervereinigung' (两德重新统一) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "-ung 结尾必为阴性名词：die Wiedervereinigung。"},
        {"id": "B1_L14_Q6", "type": "GRAMMAR_FILL", "question": "功能动词短语填空：'eine wichtige Rolle _____' (扮演关键角色 / 起重要作用)", "options": ["spielen", "haben", "geben", "machen"], "correctIndex": 0, "explanation": "eine Rolle spielen 意为起作用、扮演角色：Bildung spielt eine zentrale Rolle.（教育起着核心作用）。"},
        {"id": "B1_L14_Q7", "type": "VOCAB_MEANING", "question": "德国国庆日：'der Tag der Deutschen Einheit' 纪念日法定日期是：", "options": ["10月3日", "5月1日", "11月9日", "12月25日"], "correctIndex": 0, "explanation": "每年 10 月 3 日是德国国庆日（德国统一日，Tag der Deutschen Einheit）。"},
        {"id": "B1_L14_Q8", "type": "GRAMMAR_FILL", "question": "功能动词短语填空：'etwas in Betracht _____' (考虑到、斟酌顾及某事)", "options": ["ziehen", "nehmen", "stellen", "bringen"], "correctIndex": 0, "explanation": "in Betracht ziehen 等同于 berücksichtigen（把某事物纳入考虑范围）。"},
        {"id": "B1_L14_Q9", "type": "SENTENCE_BUILDER", "question": "功能动词短语表达“提出批评”的搭配是：", "options": ["Kritik üben an + Dativ", "Kritik machen auf + Akkusativ", "Kritik sagen zu + Dativ", "Kritik haben über + Akkusativ"], "correctIndex": 0, "explanation": "Kritik üben an + Dativ 是固定的功能动词结构，意为“对……提出批评”。"},
        {"id": "B1_L14_Q10", "type": "EXAM_REAL", "question": "德国政治制度核心知识：德意志联邦共和国由多少个联邦州 (Bundesländer) 组成？", "options": ["12 个", "16 个 (16 Bundesländer)", "20 个", "24 个"], "correctIndex": 1, "explanation": "德国是由 16 个联邦州（包含三个城市州：柏林、汉堡、不来梅）组成的联邦制议会民主国家。"}
    ],
    "B1_L15": [
        {"id": "B1_L15_Q1", "type": "EXAM_REAL", "question": "歌德 B1 听力 Teil 1 核心技巧：每段短对话播放两遍，听音前应优先：", "options": ["闭上眼睛休息", "利用给出的审题时间，快速划出两道题干中的关键核心词与否定词", "直接看答题卡", "只听第二遍"], "correctIndex": 1, "explanation": "歌德 B1 听力审题时间极短，必须争分夺秒标出题干关键限定词（时间、地点、数字、伴随人物、nicht/kein），提前预测听力录音焦点。"},
        {"id": "B1_L15_Q2", "type": "EXAM_REAL", "question": "歌德 B1 阅读 Teil 2（报刊文章长篇阅读）：针对每道选择题，最稳妥的解题顺序是：", "options": ["把全篇文章通篇精读翻译成中文后再做题", "定位题目对应的段落，寻找文中的同义改写 (Synonyme) 并排除干扰项", "直接选原文一模一样词汇出现最多的选项", "选最长的一个选项"], "correctIndex": 1, "explanation": "歌德高等级考试极少照搬原词出题，正确答案通常是原文核心信息的“同义替换改写”，而照搬原词的往往是断章取义的干扰陷阱。"},
        {"id": "B1_L15_Q3", "type": "EXAM_REAL", "question": "歌德 B1 写作 Teil 1（给朋友写私人邮件）：要求包含 3 个指导点，字数约 80 词。称谓与正文第一个单词格式规范：", "options": ["Liebe Maria!正文大写", "Liebe Maria, 正文首字母强制小写（除非是名词）", "Sehr geehrte Maria, 正文大写", "Hallo! 正文全部大写"], "correctIndex": 1, "explanation": "书信称谓以逗号结尾时（如 Liebe Maria,），紧接着的第一句首字母必须小写（名词除外）！这是德语书信书写格式死规则。"},
        {"id": "B1_L15_Q4", "type": "EXAM_REAL", "question": "歌德 B1 写作 Teil 2（在论坛就某一热点话题发表个人见解）：字数约 80 词，文章结构应当包括：", "options": ["一句话完事", "引出话题 -> 阐述个人观点与理由 -> 举出亲身经历/例证 -> 辩证总结", "只抄题目提示语", "全部写成反问句"], "correctIndex": 1, "explanation": "论坛跟帖发言必须有观点 (Meinung)、论据 (Begründung) 及生活实例 (Beispiel)，体现逻辑严密的论述结构。"},
        {"id": "B1_L15_Q5", "type": "EXAM_REAL", "question": "歌德 B1 口语 Teil 2（个人报告作 Presentation）：题目给定 5 个幻灯片步骤，不可缺少哪一步？", "options": ["跳过导入直接结尾", "介绍个人经历、自己国家的情况、优缺点对比及个人看法总结", "只讲自己国家的情况", "一句话不讲"], "correctIndex": 1, "explanation": "B1 口语报告标准 5 部曲：Meine persönlichen Erfahrungen -> Die Situation in meinem Heimatland -> Vor- und Nachteile -> Meine eigene Meinung -> Beendigung der Präsentation。"},
        {"id": "B1_L15_Q6", "type": "GRAMMAR_FILL", "question": "综合语法检阅（多层从句）：'Ich hoffe, dass das Problem bald gelöst werden _____, da alle daran arbeiten.'", "options": ["kann", "können", "konnte", "gekonnt"], "correctIndex": 0, "explanation": "被动态与情态动词复合：dass 从句中情态动词 kann 置于第二分词 gelöst 与助动词 werden 之后，位于句末。"},
        {"id": "B1_L15_Q7", "type": "GRAMMAR_FILL", "question": "综合介词检阅：'_____ des starken Schneefalls kamen viele Züge mit Verspätung an.'", "options": ["Wegen", "Trotz", "Während", "Statt"], "correctIndex": 0, "explanation": "表示暴雪天气导致晚点的因果逻辑，且支配第二格 des starken Schneefalls，用 Wegen。"},
        {"id": "B1_L15_Q8", "type": "GRAMMAR_FILL", "question": "综合虚拟语气检阅：'Wenn ich damals besser aufgepasst _____, _____ mir der Fehler nicht passiert.'", "options": ["hätte / wäre", "hätte / hätte", "wäre / wäre", "hatte / war"], "correctIndex": 0, "explanation": "aufpassen 完成时助动词用 haben -> hätte；passieren 是状态改变/不及物动词，完成时用 sein -> wäre passiert。"},
        {"id": "B1_L15_Q9", "type": "VOCAB_MEANING", "question": "口语互动汇报完毕后的标准过渡金句（向搭档与考官致意）：", "options": ["Das war meine Präsentation. Haben Sie noch Fragen oder Rückmeldungen?", "Ich bin fertig, tschüss.", "Jetzt bist du dran, red mal.", "Keine Ahnung mehr."], "correctIndex": 0, "explanation": "'Das war meine Präsentation. Ich danke Ihnen für Ihre Aufmerksamkeit und freue mich auf Ihre Fragen' 是 B1 口语汇报标准的谢幕过渡句。"},
        {"id": "B1_L15_Q10", "type": "EXAM_REAL", "question": "歌德 B1 考试四项模块（听、说、读、写）的通过与补考规则：", "options": ["必须四门一次性同时考过，挂一门全盘重考", "四门模块完全独立，通过的模块成绩长期有效，未通过的模块可单独报名重考", "不需要及格线", "口语不占分"], "correctIndex": 1, "explanation": "歌德 B1（自2013年起）采用模块化考试 (Modulare Prüfung)，听、说、读、写四个模块独立发证，单科挂科只需重考该单科。"}
    ]
}
