#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Comprehensive Quiz Bank for Level A1 (Goethe A1 Exam Standard):
15 Lessons, 10 in-depth questions per lesson = 150 total questions.
Covers articles, cases (Nom./Akk./Dat.), conjugations, modals, separable verbs,
word order, imperative, past tense (Perfekt), numbers/time, and real Goethe exam questions.
"""

A1_QUIZZES = {
    "A1_L01": [
        {"id": "A1_L01_Q1", "type": "GRAMMAR_FILL", "question": "请根据主语选择正确的动词变位：'Ich _____ aus China.'", "options": ["kommst", "komme", "kommt", "kommen"], "correctIndex": 1, "explanation": "主语为第一人称单数 ich 时，规则动词现在时词尾加 -e，故为 komme。"},
        {"id": "A1_L01_Q2", "type": "GRAMMAR_FILL", "question": "主语为 du 时，动词 lernen 的现在时正确形式是：'Wo _____ du Deutsch?'", "options": ["lerne", "lernt", "lernst", "lernen"], "correctIndex": 2, "explanation": "第二人称单数 du 的动词现在时规则词尾为 -st，故为 lernst。"},
        {"id": "A1_L01_Q3", "type": "SENTENCE_BUILDER", "question": "根据德语 V2 语序铁律，时间状语 Heute 位于句首时，正确的语序是：", "options": ["Heute ich lerne Deutsch.", "Heute lerne ich Deutsch.", "Heute lerne Deutsch ich.", "Heute Deutsch ich lerne."], "correctIndex": 1, "explanation": "陈述句中变位动词永远占在第 2 位！状语 Heute 占第 1 位，动词 lerne 必须占第 2 位，主语 ich 退居第 3 位。"},
        {"id": "A1_L01_Q4", "type": "GRAMMAR_FILL", "question": "询问国籍与籍贯时，使用哪个疑问词：'_____ kommen Sie?'", "options": ["Wo", "Woher", "Wohin", "Wie"], "correctIndex": 1, "explanation": "Woher 表示“从哪里来”（询问来源、籍贯），搭配介词 aus；Wo 表示“在哪里”；Wohin 表示“去哪里”。"},
        {"id": "A1_L01_Q5", "type": "EXAM_REAL", "question": "A: 'Kommen Sie nicht aus Deutschland?' (您难道不是来自德国吗？)\nB: '_____, ich komme aus Berlin!'", "options": ["Ja", "Nein", "Doch", "Nicht"], "correctIndex": 2, "explanation": "针对带否定词 nicht 的反问句，若要做出肯定的回答，德语中必须使用 'Doch'（不，我就是）！"},
        {"id": "A1_L01_Q6", "type": "GRAMMAR_FILL", "question": "动词 heißen 的第二人称单数 (du) 变位是：'Wie _____ du?'", "options": ["heißst", "heißt", "heiße", "heißen"], "correctIndex": 1, "explanation": "动词词干以 -s, -ß, -z 结尾时，du 变位词尾只加 -t（不加 -st），故 du heißt 与 er heißt 同形。"},
        {"id": "A1_L01_Q7", "type": "GRAMMAR_FILL", "question": "动词 arbeiten 词干以 -t 结尾，第三人称单数变位是：'Thomas _____ bei Siemens.'", "options": ["arbeitt", "arbeitet", "arbeitte", "arbeiten"], "correctIndex": 1, "explanation": "词干以 -t 或 -d 结尾的动词，在 du, er/sie/es, ihr 变位时须加 -e- 缓冲发音，故为 er arbeitet。"},
        {"id": "A1_L01_Q8", "type": "VOCAB_MEANING", "question": "单词 'die Begrüßung' 的中文意思是：", "options": ["告别、分手", "问候、寒暄、欢迎", "感谢", "道歉"], "correctIndex": 1, "explanation": "die Begrüßung 来源于 begrüßen（问候、打招呼），意为问候、寒暄。"},
        {"id": "A1_L01_Q9", "type": "LISTENING_MCQ", "question": "在正式商务场合初次与德国客户见面握手，最地道的问候语是：", "options": ["Tschüss!", "Guten Tag, sehr erfreut!", "Gute Nacht!", "Bis bald!"], "correctIndex": 1, "explanation": "正式商务社交初次相识，常用 'Guten Tag, sehr erfreut!'（日安，很高兴认识您！）。"},
        {"id": "A1_L01_Q10", "type": "SENTENCE_BUILDER", "question": "将下列词语组成正确的是非疑问句：[aus China / Sie / kommen / ?]", "options": ["Sie kommen aus China?", "Kommen Sie aus China?", "Aus China kommen Sie?", "Kommen aus China Sie?"], "correctIndex": 1, "explanation": "是非疑问句（Ja/Nein-Frage）中，变位动词必须置于句首第 1 位！主语紧随其后。"}
    ],
    "A1_L02": [
        {"id": "A1_L02_Q1", "type": "ARTICLE", "question": "名词 'Vater' (父亲) 的第一格定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "Vater 是阳性名词，第一格定冠词为 der (der Vater)。"},
        {"id": "A1_L02_Q2", "type": "ARTICLE", "question": "名词 'Mutter' (母亲) 的第一格定冠词是：", "options": ["der", "die", "das", "dem"], "correctIndex": 1, "explanation": "Mutter 是阴性名词，第一格定冠词为 die (die Mutter)。"},
        {"id": "A1_L02_Q3", "type": "ARTICLE", "question": "名词 'Kind' (孩子) 的第一格定冠词是：", "options": ["der", "die", "das", "ein"], "correctIndex": 2, "explanation": "Kind 是中性名词，第一格定冠词为 das (das Kind)。"},
        {"id": "A1_L02_Q4", "type": "GRAMMAR_FILL", "question": "名词复数：'das Kind' 变为复数形式是：", "options": ["die Kinde", "die Kinder", "die Kindern", "die Kindes"], "correctIndex": 1, "explanation": "das Kind 的复数形式是加 -er：die Kinder。"},
        {"id": "A1_L02_Q5", "type": "GRAMMAR_FILL", "question": "第一格物主代词填空：'Das ist _____ Bruder.' (我的哥哥，阳性 der)", "options": ["meine", "mein", "meinen", "meinem"], "correctIndex": 1, "explanation": "第一格阳性物主代词无词尾，与 ein 同形，故为 mein Bruder；阴性才加 -e (meine Schwester)。"},
        {"id": "A1_L02_Q6", "type": "GRAMMAR_FILL", "question": "否定词选择：'Das ist _____ Hund, das ist eine Katze.'", "options": ["nicht", "kein", "keine", "keinen"], "correctIndex": 1, "explanation": "否定带不定冠词或零冠词的名词用 kein；Hund 是阳性第一格，故为 kein Hund。"},
        {"id": "A1_L02_Q7", "type": "GRAMMAR_FILL", "question": "否定词选择：'Ich wohne _____ in Berlin.'", "options": ["kein", "keine", "nicht", "nichts"], "correctIndex": 2, "explanation": "否定动词、介词短语或副词必须用 nicht！"},
        {"id": "A1_L02_Q8", "type": "GRAMMAR_FILL", "question": "物主代词 euer 遇到阴性名词时的特殊词尾拼写是：'Ist das _____ Mutter?' (你们的母亲)", "options": ["euere", "eure", "euer", "euren"], "correctIndex": 1, "explanation": "euer 在加词尾 -e 时，中间的 -e- 必须脱落，拼写作 eure Mutter (非 *euere)！"},
        {"id": "A1_L02_Q9", "type": "VOCAB_MEANING", "question": "单词 'die Geschwister' (复数) 的意思是：", "options": ["祖父母", "兄弟姐妹（合称）", "父母亲", "夫妻"], "correctIndex": 1, "explanation": "die Geschwister 是复数名词，泛指兄弟姐妹。例如：Ich habe zwei Geschwister."},
        {"id": "A1_L02_Q10", "type": "EXAM_REAL", "question": "看图/填空：'Sind Sie verheiratet?' 最符合语境的回答是：", "options": ["Nein, ich bin ledig.", "Ja, ich komme aus Spanien.", "Ich heiße Anna.", "Danke gut!"], "correctIndex": 0, "explanation": "verheiratet 意为“已婚的”，其对立状态词为 ledig（单身的）或 geschieden（离异的）。"}
    ],
    "A1_L03": [
        {"id": "A1_L03_Q1", "type": "GRAMMAR_FILL", "question": "第四格 (Akkusativ) 填空：'Ich trinke jeden Morgen _____ Kaffee.' (阳性 der Kaffee)", "options": ["ein", "einen", "eine", "einem"], "correctIndex": 1, "explanation": "及物动词 trinken 支配第四格。在第四格中，阳性冠词 der -> den, ein -> einen！"},
        {"id": "A1_L03_Q2", "type": "GRAMMAR_FILL", "question": "第四格中性名词填空：'Er kauft _____ Buch.' (中性 das Buch)", "options": ["einen", "ein", "eine", "einem"], "correctIndex": 1, "explanation": "中性名词在第四格中与第一格完全相同，保持 ein Buch (das Buch)。"},
        {"id": "A1_L03_Q3", "type": "GRAMMAR_FILL", "question": "第四格阴性名词填空：'Wir essen _____ Banane.' (阴性 die Banane)", "options": ["ein", "einen", "eine", "einer"], "correctIndex": 2, "explanation": "阴性名词在第四格中形态不变，保持 eine Banane (die Banane)。"},
        {"id": "A1_L03_Q4", "type": "GRAMMAR_FILL", "question": "句型 Es gibt + Akkusativ 填空：'In der Stadt gibt es _____ großen Park.' (阳性 der Park)", "options": ["ein", "einen", "einem", "einer"], "correctIndex": 1, "explanation": "固定句型 Es gibt 必须强制支配第四格！阳性名词 der Park 变为 einen großen Park。"},
        {"id": "A1_L03_Q5", "type": "GRAMMAR_FILL", "question": "人称代词第四格：'Ich kenne den Mann nicht. Kennst du _____?'", "options": ["er", "ihn", "ihm", "sie"], "correctIndex": 1, "explanation": "er 的第四格形式是 ihn。代词指代阳性名词 den Mann。"},
        {"id": "A1_L03_Q6", "type": "ARTICLE", "question": "名词 'Apfel' (苹果) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "Apfel 是阳性名词：der Apfel (Pl. die Äpfel)。"},
        {"id": "A1_L03_Q7", "type": "VOCAB_MEANING", "question": "超市食材：'das Gemüse' 的中文含义是：", "options": ["水果", "蔬菜", "肉类", "面包"], "correctIndex": 1, "explanation": "das Gemüse 是集合名词，意为“蔬菜”；水果是 das Obst。"},
        {"id": "A1_L03_Q8", "type": "GRAMMAR_FILL", "question": "否定第四格阳性名词：'Ich habe heute leider _____ Hunger.' (阳性 der Hunger)", "options": ["nicht", "kein", "keinen", "keine"], "correctIndex": 2, "explanation": "Hunger 为阳性名词，在 haben 后作第四格宾语，否定冠词变为 keinen Hunger。"},
        {"id": "A1_L03_Q9", "type": "SENTENCE_BUILDER", "question": "超市结账选词组合：'Ich möchte bitte _____ Kilo Tomaten.'", "options": ["ein", "einen", "eine", "eines"], "correctIndex": 0, "explanation": "das Kilo（公斤）是中性名词，作第四格依然是 ein Kilo。"},
        {"id": "A1_L03_Q10", "type": "EXAM_REAL", "question": "歌德 A1 听力高频对话：'Brauchen Sie eine Tüte?' 顾客的最佳回应是：", "options": ["Ja, bitte, das kostet zwei Euro.", "Nein, danke, ich habe eine Tasche dabei.", "Ich trinke Tee.", "Sehr angenehm!"], "correctIndex": 1, "explanation": "收银员问“您需要塑料袋/购物袋吗？”，礼貌回答为“不用了谢谢，我自带了包”。"}
    ],
    "A1_L04": [
        {"id": "A1_L04_Q1", "type": "GRAMMAR_FILL", "question": "情态动词 möchten 变位：'Ich _____ gern ein Mineralwasser.'", "options": ["möchtet", "möchte", "möchtest", "möchten"], "correctIndex": 1, "explanation": "第一人称单数 ich 的变位为 möchte（注意：第一和第三人称单数同形，无 -t！）。"},
        {"id": "A1_L04_Q2", "type": "GRAMMAR_FILL", "question": "对您 (Sie) 的尊称命令式构成：'_____ Sie bitte hier Platz!' (nehmen)", "options": ["Nehmt", "Nimm", "Nehmen", "Nehme"], "correctIndex": 2, "explanation": "尊称 Sie 的命令式为动词原形居首 + Sie：Nehmen Sie bitte Platz! (请坐！)"},
        {"id": "A1_L04_Q3", "type": "GRAMMAR_FILL", "question": "助动词 sein 对 Sie 的尊称命令式特殊形式是：'_____ Sie bitte leise!'", "options": ["Sind", "Seid", "Seien", "Sei"], "correctIndex": 2, "explanation": "sein 对 Sie 的命令式是特殊形式 Seien Sie bitte ...！"},
        {"id": "A1_L04_Q4", "type": "EXAM_REAL", "question": "在德国餐厅用餐完毕买单时，服务员常问：'Zusammen oder getrennt?' 意思是：", "options": ["要米饭还是面条？", "一起结账还是分开结账？", "现金还是刷卡？", "好吃还是不好吃？"], "correctIndex": 1, "explanation": "zusammen (合在一起付) vs getrennt (AA制各自付)，是德语区餐厅买单最核心交际句。"},
        {"id": "A1_L04_Q5", "type": "LISTENING_MCQ", "question": "给餐厅服务员小费时，若账单是 18 欧元，给 20 欧元并说：'_____!' 意为不用找零。", "options": ["Guten Appetit", "Stimmt so", "Auf Wiedersehen", "Prost"], "correctIndex": 1, "explanation": "'Stimmt so!' 是德语区结账给出小费的标准口语习惯用语，意为“就这样找零不用了”。"},
        {"id": "A1_L04_Q6", "type": "GRAMMAR_FILL", "question": "情态动词 möchten 第二人称复数 ihr 变位：'Was _____ ihr trinken?'", "options": ["möchte", "möchtest", "möchtet", "möchten"], "correctIndex": 2, "explanation": "ihr 的变位加词尾 -t，故为 möchtet。"},
        {"id": "A1_L04_Q7", "type": "VOCAB_MEANING", "question": "餐桌礼仪：'Guten Appetit!' 的中文含义是：", "options": ["干杯！", "祝您胃口好/请慢用！", "祝您旅途愉快！", "再见！"], "correctIndex": 1, "explanation": "Guten Appetit! 在开饭前对同桌人说，意为“祝用餐愉快/慢用”。祝酒说 Prost! 或 Zum Wohl!"},
        {"id": "A1_L04_Q8", "type": "GRAMMAR_FILL", "question": "极客气的点餐虚拟式句型：'Ich _____ gern ein Schnitzel mit Pommes.'", "options": ["habe", "hätte", "hatte", "bin"], "correctIndex": 1, "explanation": "Ich hätte gern ... (haben 的第二虚拟式) 比 Ich will ... 礼貌得多，是德语区最纯正的点餐金句。"},
        {"id": "A1_L04_Q9", "type": "ARTICLE", "question": "名词 'Rechnung' (账单) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "以 -ung 结尾的名词必为阴性名词：die Rechnung。"},
        {"id": "A1_L04_Q10", "type": "EXAM_REAL", "question": "向服务员索要菜单的得体说法是：", "options": ["Geben Sie Speisekarte!", "Die Speisekarte, bitte!", "Ich will essen.", "Wo ist Essen?"], "correctIndex": 1, "explanation": "在德语中，使用带有 bitte 的精练短语 'Die Speisekarte, bitte!' 礼貌而自然。"}
    ],
    "A1_L05": [
        {"id": "A1_L05_Q1", "type": "GRAMMAR_FILL", "question": "第三格 (Dativ) 阳性冠词变化：'Das Auto gehört _____ Vater.' (阳性 der Vater)", "options": ["den", "dem", "des", "der"], "correctIndex": 1, "explanation": "纯支配第三格动词 gehören（属于）。第三格阳性定冠词为 dem！"},
        {"id": "A1_L05_Q2", "type": "GRAMMAR_FILL", "question": "第三格阴性冠词变化：'Ich helfe _____ Frau.' (阴性 die Frau)", "options": ["dem", "der", "den", "die"], "correctIndex": 1, "explanation": "动词 helfen 支配第三格。第三格阴性定冠词变为 der！"},
        {"id": "A1_L05_Q3", "type": "GRAMMAR_FILL", "question": "第三格复数名词必须加 -n 铁律：'Ich antworte den _____.' (der Student, Pl. die Studenten)", "options": ["Student", "Studenten", "Studenter", "Studentes"], "correctIndex": 1, "explanation": "第三格复数冠词为 den，且名词末尾必须补加 -n。"},
        {"id": "A1_L05_Q4", "type": "GRAMMAR_FILL", "question": "问候动词与第三格搭配：'Wie geht es _____?' (你，du)", "options": ["du", "dich", "dir", "dein"], "correctIndex": 2, "explanation": "固定句型 Wie geht es + Dativ？第二人称单数 du 的第三格形式为 dir。"},
        {"id": "A1_L05_Q5", "type": "GRAMMAR_FILL", "question": "人称代词第三格：'Der Lehrer dankt _____.' (我们，wir)", "options": ["wir", "uns", "euch", "ihnen"], "correctIndex": 1, "explanation": "danken 支配第三格，wir 的第三格代词形式是 uns。"},
        {"id": "A1_L05_Q6", "type": "GRAMMAR_FILL", "question": "介词 in + dem 的高频缩合形式是：'Er schläft _____ Schlafzimmer.'", "options": ["ins", "im", "am", "zum"], "correctIndex": 1, "explanation": "静态方位 in + dem (中性 das Schlafzimmer) 缩合为 im。"},
        {"id": "A1_L05_Q7", "type": "GRAMMAR_FILL", "question": "介词 zu + der 的高频缩合形式是：'Ich gehe _____ Bank.' (阴性 die Bank)", "options": ["zum", "zur", "im", "ans"], "correctIndex": 1, "explanation": "zu 永远支配第三格，zu + der (阴性) 缩合为 zur (zur Bank, zur Schule)。"},
        {"id": "A1_L05_Q8", "type": "VOCAB_MEANING", "question": "动词 'gefallen' 的用法与汉语表达习惯相反，在句子 'Die Wohnung gefällt mir gut.' 中，主语是：", "options": ["ich", "mir", "Die Wohnung", "gut"], "correctIndex": 2, "explanation": "gefallen 是“物使人中意”，物作第一格主语 (Die Wohnung)，人作第三格 (mir)。"},
        {"id": "A1_L05_Q9", "type": "ARTICLE", "question": "名词 'Küche' (厨房) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "以 -e 结尾的很多日常名词为阴性：die Küche。"},
        {"id": "A1_L05_Q10", "type": "EXAM_REAL", "question": "租房广告看懂关键术语：'Warmmiete' (暖租) 包含什么？", "options": ["只有房租净价", "包含房租净价 (Kaltmiete) 以及暖气物业等杂费 (Nebenkosten)", "只包含电费", "包含家具费"], "correctIndex": 1, "explanation": "die Warmmiete 指包含了暖气、垃圾处理、水费等杂费的总租金；Kaltmiete 指裸租净价。"}
    ],
    "A1_L06": [
        {"id": "A1_L06_Q1", "type": "GRAMMAR_FILL", "question": "可分动词 aufstehen 的框形结构：'Ich _____ jeden Tag um 7 Uhr _____.'", "options": ["stehe ... auf", "aufstehe ... ", "steht ... auf", "gestanden ... auf"], "correctIndex": 0, "explanation": "一般现在时中，可分动词的前缀与词干脱离，前缀 auf 必须被甩到整个句子的最末尾！"},
        {"id": "A1_L06_Q2", "type": "GRAMMAR_FILL", "question": "时间介词填空（具体点钟）：'Der Film beginnt _____ 20:15 Uhr.'", "options": ["am", "um", "im", "in"], "correctIndex": 1, "explanation": "具体钟点时刻 (Uhrzeit) 前统一使用介词 um！"},
        {"id": "A1_L06_Q3", "type": "GRAMMAR_FILL", "question": "时间介词填空（星期几/具体日期）：'Wir treffen uns _____ Samstag.'", "options": ["um", "am", "im", "ab"], "correctIndex": 1, "explanation": "星期几、具体日期和一天中的时段（除夜里外）前统一使用介词 am (an dem)！"},
        {"id": "A1_L06_Q4", "type": "GRAMMAR_FILL", "question": "时间介词填空（月份/季节）：'Ich habe _____ Juli Geburtstag.'", "options": ["um", "am", "im", "von"], "correctIndex": 2, "explanation": "月份和季节前统一使用介词 im (in dem)！如 im Juli, im Sommer。"},
        {"id": "A1_L06_Q5", "type": "GRAMMAR_FILL", "question": "时间起止介词搭配：'Die Bank ist _____ 9:00 _____ 16:00 Uhr geöffnet.'", "options": ["von ... bis", "ab ... zu", "seit ... nach", "um ... am"], "correctIndex": 0, "explanation": "表达时间从某点到某点，使用固定成对介词 von ... bis ...。"},
        {"id": "A1_L06_Q6", "type": "GRAMMAR_FILL", "question": "可分动词 anrufen 一般疑问句语序：'_____ du deine Mutter _____?'", "options": ["Anrufst ... ", "Rufst ... an", "Rufst ... auf", "Rufen ... an"], "correctIndex": 1, "explanation": "疑问句中变位动词 rufst 提至句首第 1 位，前缀 an 依然坚守在句末。"},
        {"id": "A1_L06_Q7", "type": "VOCAB_MEANING", "question": "可分动词 'einkaufen' 与及物动词 'kaufen' 的细微区别在于：", "options": ["两者无区别", "einkaufen 常用于指超市/生活用品采购购物（不及物或绝对用法）", "einkaufen 只能买车", "kaufen 只能买书"], "correctIndex": 1, "explanation": "einkaufen 常独立使用表示日常采买（如 Wir kaufen am Samstag ein），而 kaufen 通常必须带具体的第四格宾语（Ich kaufe ein Auto）。"},
        {"id": "A1_L06_Q8", "type": "PRONUNCIATION", "question": "在可分动词 'aufstehen' 原形中，单词重音落在哪里？", "options": ["在词根 steh- 上", "在可分前缀 auf- 上", "在词尾 -en 上", "无重音"], "correctIndex": 1, "explanation": "德语可分动词的前缀在动词原形中必须重读！如 ˈaufstehen, ˈanrufen。"},
        {"id": "A1_L06_Q9", "type": "GRAMMAR_FILL", "question": "特殊时间搭配（夜里）：'Er arbeitet _____.'", "options": ["am Nacht", "im Nacht", "in der Nacht", "um Nacht"], "correctIndex": 2, "explanation": "一天中的时段通常用 am（am Morgen, am Abend），唯独夜里是固定短语 in der Nacht！"},
        {"id": "A1_L06_Q10", "type": "EXAM_REAL", "question": "看懂预约日程：'Einen Termin vereinbaren' 意思是：", "options": ["取消预约", "约定/确定一个预约时间", "推迟预约", "错过预约"], "correctIndex": 1, "explanation": "einen Termin vereinbaren 是办事看病高频词组，意为“约定时间”；取消是 absagen，推迟是 verschieben。"}
    ],
    "A1_L07": [
        {"id": "A1_L07_Q1", "type": "GRAMMAR_FILL", "question": "情态动词 können 第一人称单数 (ich) 变位：'Ich _____ gut schwimmen.'", "options": ["könne", "kann", "kannst", "könnt"], "correctIndex": 1, "explanation": "können 单数人称变位元音变为 a，第一和第三人称单数同形为 kann（无词尾 -t）。"},
        {"id": "A1_L07_Q2", "type": "SENTENCE_BUILDER", "question": "含有情态动词的句子，实义动词必须放在句子的什么位置？", "options": ["紧跟在情态动词后面", "句子最末尾，以原形 (Infinitiv) 出现", "句子开头", "随意放置"], "correctIndex": 1, "explanation": "情态动词框形结构铁律：变位情态动词占第 2 位，实义动词以原形 (Infinitiv) 永远被甩到句末！"},
        {"id": "A1_L07_Q3", "type": "GRAMMAR_FILL", "question": "德语女性职业名词构成规则：'der Lehrer' (男老师) 对应的女老师是：", "options": ["das Lehrermädchen", "die Lehrerin", "die Lehrerfrau", "die Lehrer"], "correctIndex": 1, "explanation": "绝大多数职业名词在男性词干后加后缀 -in 构成女性职业词，复数加 -innen。"},
        {"id": "A1_L07_Q4", "type": "GRAMMAR_FILL", "question": "职业陈述零冠词法则：'Ich bin _____.'", "options": ["ein Arzt", "der Arzt", "Arzt", "einen Arzt"], "correctIndex": 2, "explanation": "在陈述自己或他人的职业身份时，名词前通常不用冠词（零冠词）：Ich bin Arzt / Ich arbeite als Ingenieur."},
        {"id": "A1_L07_Q5", "type": "GRAMMAR_FILL", "question": "介词 als 在职业表达中的用法：'Er arbeitet _____ Ingenieur bei BMW.'", "options": ["wie", "als", "für", "von"], "correctIndex": 1, "explanation": "arbeiten als + 职业名词，表示“作为...工作/担任...职务”。"},
        {"id": "A1_L07_Q6", "type": "GRAMMAR_FILL", "question": "情态动词 können 第三人称单数：'Mein Sohn _____ schon Deutsch sprechen.'", "options": ["kann", "könnt", "kannst", "können"], "correctIndex": 0, "explanation": "er/sie/es kann，绝不能加 -t（不是 *kannt）！"},
        {"id": "A1_L07_Q7", "type": "VOCAB_MEANING", "question": "办公文具：'der Drucker' 的中文含义是：", "options": ["复印机", "打印机", "电脑屏幕", "订书机"], "correctIndex": 1, "explanation": "der Drucker 来源于 drucken（打印），意为打印机。"},
        {"id": "A1_L07_Q8", "type": "ARTICLE", "question": "名词 'Büro' (办公室) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "Büro 是中性名词：das Büro (Pl. die Büros)。"},
        {"id": "A1_L07_Q9", "type": "SENTENCE_BUILDER", "question": "语序重组：[kann / sehr gut / mein Kollege / programmieren]", "options": ["Mein Kollege kann sehr gut programmieren.", "Mein Kollege programmieren kann sehr gut.", "Kann mein Kollege programmieren sehr gut.", "Sehr gut mein Kollege kann programmieren."], "correctIndex": 0, "explanation": "情态动词 kann 在第 2 位，实义动词原形 programmieren 必须在句末。"},
        {"id": "A1_L07_Q10", "type": "EXAM_REAL", "question": "求职面试回答技能：'Welche Sprachen sprechen Sie?' 规范回答是：", "options": ["Ich kann Deutsch und Englisch.", "Ich heiße Michael.", "Ich wohne in Frankfurt.", "Mein Hobby ist Fußball."], "correctIndex": 0, "explanation": "回答语种技能可用 sprechen 或情态动词 können + 语言名称。"}
    ],
    "A1_L08": [
        {"id": "A1_L08_Q1", "type": "GRAMMAR_FILL", "question": "身体疼痛表达（单数部位）：'Mein Kopf _____ weh.'", "options": ["tut", "tun", "macht", "hat"], "correctIndex": 0, "explanation": "身体单数部位主语搭配 tut weh (Mein Kopf tut weh)；复数部位搭配 tun weh。"},
        {"id": "A1_L08_Q2", "type": "GRAMMAR_FILL", "question": "身体疼痛表达（复数部位）：'Meine Beine _____ weh.'", "options": ["tut", "tun", "sind", "haben"], "correctIndex": 1, "explanation": "复数主语 Meine Beine（双腿）与动词复数一致，搭配 tun weh。"},
        {"id": "A1_L08_Q3", "type": "GRAMMAR_FILL", "question": "情态动词 müssen 变位：'Du hast hohes Fieber. Du _____ zum Arzt gehen!'", "options": ["musst", "musstet", "müsst", "muss"], "correctIndex": 0, "explanation": "müssen 对 du 的变位为 musst（去变音 ü 变 u）。"},
        {"id": "A1_L08_Q4", "type": "GRAMMAR_FILL", "question": "转述医嘱使用情态动词 sollen：'Der Arzt sagt, ich _____ viel Wasser trinken.'", "options": ["muss", "soll", "will", "darf"], "correctIndex": 1, "explanation": "传达医生、上司等第三方要求或嘱咐时，德语习惯使用情态动词 sollen！"},
        {"id": "A1_L08_Q5", "type": "GRAMMAR_FILL", "question": "禁止与非必要辨析：'Hier _____ man nicht rauchen!' (此处严禁吸烟)", "options": ["muss", "darf", "soll", "kann"], "correctIndex": 1, "explanation": "nicht dürfen 表示法定义务严禁、绝不允许；而 nicht müssen 仅表示“不必、不需要”。"},
        {"id": "A1_L08_Q6", "type": "VOCAB_MEANING", "question": "词汇：'die Krankschreibung' 在德国职场生活中是：", "options": ["病历本", "医生开具的官方病假证明单", "处方药方", "挂号单"], "correctIndex": 1, "explanation": "die Krankschreibung 是向雇主请病假必须提交的医生休假诊断证明。"},
        {"id": "A1_L08_Q7", "type": "ARTICLE", "question": "名词 'Medikament' (药物) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "以 -ment 结尾的外来词多为中性：das Medikament (Pl. die Medikamente)。"},
        {"id": "A1_L08_Q8", "type": "EXAM_REAL", "question": "医生问诊第一句话：'Was fehlt Ihnen denn?' 含义是：", "options": ["您缺了什么东西？", "您哪里不舒服？/ 怎么了？", "您想要什么药？", "您几岁了？"], "correctIndex": 1, "explanation": "'Was fehlt Ihnen?' 是德语医生接诊患者的经典开场白，等同于 Wie kann ich Ihnen helfen? / Wo haben Sie Schmerzen?"},
        {"id": "A1_L08_Q9", "type": "GRAMMAR_FILL", "question": "情态动词 sollen 第三人称单数：'Das Kind _____ im Bett bleiben.'", "options": ["sollt", "soll", "sollte", "sollen"], "correctIndex": 1, "explanation": "er/sie/es soll，情态动词一三单数无词尾。"},
        {"id": "A1_L08_Q10", "type": "LISTENING_MCQ", "question": "药店买药指示：'Nehmen Sie die Tablette dreimal täglich vor dem Essen!' 应该在什么时候服药？", "options": ["每天饭后三次", "每天饭前三次", "每天早晨一次", "睡前服药"], "correctIndex": 1, "explanation": "vor dem Essen 意为“饭前”，dreimal täglich 意为“每天三次”。"}
    ],
    "A1_L09": [
        {"id": "A1_L09_Q1", "type": "GRAMMAR_FILL", "question": "乘坐交通工具介词 mit + Dativ：'Ich fahre _____ Bus.' (阳性 der Bus)", "options": ["mit den", "mit dem", "mit der", "mit das"], "correctIndex": 1, "explanation": "mit 永远支配第三格！der Bus 变为 dem Bus (mit dem Bus)。"},
        {"id": "A1_L09_Q2", "type": "GRAMMAR_FILL", "question": "乘坐火车/铁路：'Wir fahren _____ Bahn.' (阴性 die Bahn)", "options": ["mit der", "mit dem", "mit den", "in der"], "correctIndex": 0, "explanation": "die Bahn 变为第三格 der Bahn (mit der Bahn)。"},
        {"id": "A1_L09_Q3", "type": "GRAMMAR_FILL", "question": "表达“步行/走路去”是固定搭配：'Er geht jeden Tag _____ zur Arbeit.'", "options": ["mit Fuß", "zu Fuß", "am Fuß", "auf Fuß"], "correctIndex": 1, "explanation": "步行统一使用固定短语 zu Fuß！"},
        {"id": "A1_L09_Q4", "type": "GRAMMAR_FILL", "question": "对你 (du) 的祈使句生成规则（动词 kommen）：'_____ bitte hierher!'", "options": ["Kommst", "Komm", "Kommen", "Komme"], "correctIndex": 1, "explanation": "du 祈使句：以 du 变位 kommst 为基础，砍掉代词 du 和词尾 -st，得到 Komm!"},
        {"id": "A1_L09_Q5", "type": "GRAMMAR_FILL", "question": "换音动词 (e->i) 对 du 的祈使句保留换音（动词 lesen）：'_____ das Buch laut vor!'", "options": ["Les", "Lies", "Liest", "Lese"], "correctIndex": 1, "explanation": "词干 e 变为 i/ie 的动词在 du 祈使句中【必须保留换音】：du liest -> Lies! 又如 helfen -> Hilf!"},
        {"id": "A1_L09_Q6", "type": "GRAMMAR_FILL", "question": "变音动词 (a->ä) 对 du 的祈使句脱落变音（动词 fahren）：'_____ bitte vorsichtig!'", "options": ["Fähr", "Fahr", "Fahrst", "Fahre"], "correctIndex": 1, "explanation": "词干 a 变为 ä 的动词在祈使句中【变音必须脱落还原为 a】：du fährst -> Fahr!"},
        {"id": "A1_L09_Q7", "type": "GRAMMAR_FILL", "question": "对你们 (ihr) 的祈使句生成规则（动词 machen）：'_____ die Hausaufgaben!'", "options": ["Macht", "Machst", "Machen", "Mach"], "correctIndex": 0, "explanation": "ihr 祈使句直接保留 ihr 变位动词，只需省略人称代词 ihr：Macht!"},
        {"id": "A1_L09_Q8", "type": "GRAMMAR_FILL", "question": "目的地介词选择（无冠词城市/国家）：'Wir fliegen morgen _____ Berlin.'", "options": ["in", "zu", "nach", "auf"], "correctIndex": 2, "explanation": "去往无冠词的城市、国家以及方位方向，统一使用介词 nach！"},
        {"id": "A1_L09_Q9", "type": "VOCAB_MEANING", "question": "交通换乘：动词 'umsteigen' 的意思是：", "options": ["上车", "下车", "换乘/转车", "出发"], "correctIndex": 2, "explanation": "einsteigen (上车), aussteigen (下车), umsteigen (换乘)。"},
        {"id": "A1_L09_Q10", "type": "EXAM_REAL", "question": "火车站问路问询：'Wie komme ich zum Bahnsteig 4?' 最契合的回答是：", "options": ["Nehmen Sie die Treppe nach oben!", "Um 12 Uhr.", "Das kostet 5 Euro.", "Gute Reise!"], "correctIndex": 0, "explanation": "问去4号站台怎么走，回答给出具体方向“走楼梯上去”。"}
    ],
    "A1_L10": [
        {"id": "A1_L10_Q1", "type": "GRAMMAR_FILL", "question": "指示代词 dieser 四格阳性：'Ich nehme _____ Mantel.' (阳性 der Mantel)", "options": ["dieser", "diesen", "diesem", "dieses"], "correctIndex": 1, "explanation": "dies- 词尾与定冠词完全一致。第四格阳性 der -> den，故为 diesen Mantel。"},
        {"id": "A1_L10_Q2", "type": "GRAMMAR_FILL", "question": "指示代词中性：'_____ Kleid gefällt mir sehr gut.' (中性 das Kleid)", "options": ["Dieser", "Diese", "Dieses", "Diesen"], "correctIndex": 2, "explanation": "中性第一格定冠词为 das，故为 dieses Kleid。"},
        {"id": "A1_L10_Q3", "type": "GRAMMAR_FILL", "question": "动词 passen (尺码合适) 搭配第三格：'Die Schuhe passen _____ nicht.' (我，ich)", "options": ["mich", "mir", "mein", "ich"], "correctIndex": 1, "explanation": "passen 支配第三格，表示尺寸松紧适合某人，ich 的第三格为 mir。"},
        {"id": "A1_L10_Q4", "type": "VOCAB_MEANING", "question": "动词 stehen 在服饰搭配中的特有含义：'Die rote Bluse steht dir sehr gut!'", "options": ["站立在桌边", "（颜色/款式与气质）相衬、好看", "尺码太小", "价格昂贵"], "correctIndex": 1, "explanation": "etwas steht jemandem (Dat.) gut 专指某件衣物穿在某人身上很衬、漂亮好看。"},
        {"id": "A1_L10_Q5", "type": "ARTICLE", "question": "名词 'Hose' (裤子) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "die Hose (Pl. die Hosen)。注意德语中一条裤子是单数 die Hose，不像英语用复数 trousers。"},
        {"id": "A1_L10_Q6", "type": "GRAMMAR_FILL", "question": "疑问代词 welcher 选词：'_____ Pullover gefällt dir am besten?' (阳性 der Pullover)", "options": ["Welche", "Welches", "Welcher", "Welchen"], "correctIndex": 2, "explanation": "第一格阳性定冠词为 der，疑问代词对应为 welcher。"},
        {"id": "A1_L10_Q7", "type": "VOCAB_MEANING", "question": "商场词汇：'die Umkleidekabine' 是指：", "options": ["收银台", "试衣间", "自动扶梯", "洗手间"], "correctIndex": 1, "explanation": "die Umkleidekabine 来源于 umkleiden（换衣），指试衣间。"},
        {"id": "A1_L10_Q8", "type": "GRAMMAR_FILL", "question": "表达尺寸尺码大一号：'Haben Sie diese Jacke eine Nummer _____?'", "options": ["groß", "größer", "am größten", "große"], "correctIndex": 1, "explanation": "eine Nummer größer 意为“大一码”；小一码为 eine Nummer kleiner。"},
        {"id": "A1_L10_Q9", "type": "ARTICLE", "question": "名词 'Hemd' (衬衫) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 2, "explanation": "das Hemd (Pl. die Hemden)。"},
        {"id": "A1_L10_Q10", "type": "EXAM_REAL", "question": "试穿询问：'Kann ich diesen Anzug _____?' (试穿)", "options": ["ausziehen", "anprobieren", "mitbringen", "zumachen"], "correctIndex": 1, "explanation": "anprobieren 专指在商场“试穿（衣物鞋帽）”。"}
    ],
    "A1_L11": [
        {"id": "A1_L11_Q1", "type": "GRAMMAR_FILL", "question": "情态动词 wollen 变位：'Ich _____ am Wochenende wandern gehen.'", "options": ["wollt", "will", "wille", "wollte"], "correctIndex": 1, "explanation": "wollen 第一人称单数词干元音 o 变为 i，即 ich will。"},
        {"id": "A1_L11_Q2", "type": "GRAMMAR_FILL", "question": "情态动词 dürfen 变位：'Hier _____ man nicht parken!'", "options": ["darf", "durft", "dürft", "darfst"], "correctIndex": 0, "explanation": "er/sie/es/man darf，单数元音 ü 变为 a，一三单数无词尾。"},
        {"id": "A1_L11_Q3", "type": "SENTENCE_BUILDER", "question": "喜好表达三级跳 (gern -> lieber -> am liebsten)：'Ich schwimme gern, aber ich spiele _____ Fußball.'", "options": ["am liebsten", "lieber", "besser", "mehr"], "correctIndex": 1, "explanation": "表示两者对比更喜欢用 lieber；最喜欢用 am liebsten。"},
        {"id": "A1_L11_Q4", "type": "SENTENCE_BUILDER", "question": "根据德语状语次序原则（时间先于地点 Temporal vor Lokal），正确句子是：", "options": ["Wir spielen im Park heute Fußball.", "Wir spielen heute im Park Fußball.", "Wir spielen Fußball im Park heute.", "Heute wir spielen im Park Fußball."], "correctIndex": 1, "explanation": "时间状语 heute 必须排在地点状语 im Park 之前！"},
        {"id": "A1_L11_Q5", "type": "GRAMMAR_FILL", "question": "情态动词 wollen 第三人称单数：'Michael _____ nach Italien reisen.'", "options": ["will", "willt", "wollt", "wollen"], "correctIndex": 0, "explanation": "er will，绝不能加 -t（不是 *willt）！"},
        {"id": "A1_L11_Q6", "type": "VOCAB_MEANING", "question": "词汇：'das Ehrenamt' 在德国社会指：", "options": ["全职工作", "志愿服务、无偿义工职位", "荣誉头衔", "兼职小时工"], "correctIndex": 1, "explanation": "das Ehrenamt 是德国社会极核心概念，指自愿担当的无报酬社会公益职务。"},
        {"id": "A1_L11_Q7", "type": "ARTICLE", "question": "名词 'Urlaub' (度假/休假) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 0, "explanation": "der Urlaub (Urlaub machen 度假)。"},
        {"id": "A1_L11_Q8", "type": "GRAMMAR_FILL", "question": "禁止句型：'Darf man hier Fotos machen?' - 'Nein, das ist streng _____!'", "options": ["erlaubt", "verboten", "möglich", "richtig"], "correctIndex": 1, "explanation": "verboten（被禁止的）与 dürfen nicht 对应；erlaubt 是允许的。"},
        {"id": "A1_L11_Q9", "type": "SENTENCE_BUILDER", "question": "情态动词 dürfen 一般疑问句：'_____ ich Sie etwas fragen?'", "options": ["Darf", "Dürfe", "Darfst", "Will"], "correctIndex": 0, "explanation": "Darf ich ...? 是向对方请求许可或礼貌插话的标准起首句。"},
        {"id": "A1_L11_Q10", "type": "EXAM_REAL", "question": "周末邀约对话：'Hast du Lust, heute Abend ins Kino zu gehen?' 赞同的回应是：", "options": ["Ja, gerne! Gute Idee!", "Nein, ich heiße Peter.", "Ich habe keine Zeit, danke gut.", "Das ist teuer."], "correctIndex": 0, "explanation": "Lust haben 意为“有兴趣/有兴致”，热烈赞同说 'Ja, gerne! Gute Idee!'。"}
    ],
    "A1_L12": [
        {"id": "A1_L12_Q1", "type": "GRAMMAR_FILL", "question": "天气现象句型：'Heute _____ es den ganzen Tag.' (下雨)", "options": ["regnet", "schneit", "scheint", "macht"], "correctIndex": 0, "explanation": "下雨动词为 regnen，与形式主语 es 搭配为 Es regnet。"},
        {"id": "A1_L12_Q2", "type": "GRAMMAR_FILL", "question": "体温/感受表达（极高频易错）：'_____ ist kalt.' (我觉得冷)", "options": ["Ich", "Mich", "Mir", "Mein"], "correctIndex": 2, "explanation": "表达冷热生理体感，必须用第三格：Mir ist kalt！绝不能说 *Ich bin kalt（含义变成“我这人冷酷无情”或“已死亡”）。"},
        {"id": "A1_L12_Q3", "type": "GRAMMAR_FILL", "question": "天气形容词作表语：'Im Sommer ist es in Frankfurt oft _____.'", "options": ["kalt", "sonnig und heiß", "geschneit", "wolkig regnen"], "correctIndex": 1, "explanation": "夏天法兰克福通常晴朗炎热：sonnig und heiß。"},
        {"id": "A1_L12_Q4", "type": "ARTICLE", "question": "名词 'Sonne' (太阳) 的定冠词是：", "options": ["der", "die", "das", "den"], "correctIndex": 1, "explanation": "die Sonne (Die Sonne scheint 阳光明媚)。"},
        {"id": "A1_L12_Q5", "type": "GRAMMAR_FILL", "question": "气温读法：'Heute haben wir 20 _____.' (摄氏度)", "options": ["Uhr", "Grad", "Meter", "Kilo"], "correctIndex": 1, "explanation": "温度单位使用 Grad：20 Grad (zwanzig Grad Celsius)。"},
        {"id": "A1_L12_Q6", "type": "ARTICLE", "question": "名词 'Wind' (风) 的定冠词是：", "options": ["der", "die", "das", "dem"], "correctIndex": 0, "explanation": "大部分气象自然风象名词为阳性：der Wind, der Regen, der Schnee。"},
        {"id": "A1_L12_Q7", "type": "GRAMMAR_FILL", "question": "零下气温读法：'-5°C' 读作：", "options": ["minus fünf Grad", "weniger fünf Grad", "unter fünf Uhr", "nicht fünf Grad"], "correctIndex": 0, "explanation": "零下温度统一使用 minus：minus fünf Grad。"},
        {"id": "A1_L12_Q8", "type": "VOCAB_MEANING", "question": "气象词汇：'bewölkt' 的含义是：", "options": ["晴朗无云的", "多云的、阴天的", "狂风暴雨的", "下大雪的"], "correctIndex": 1, "explanation": "bewölkt 来源于 die Wolke（云彩），意为多云的、阴天。"},
        {"id": "A1_L12_Q9", "type": "GRAMMAR_FILL", "question": "动词 scheinen (照耀) 搭配：'Der Himmel ist blau und die Sonne _____.'", "options": ["regnet", "scheint", "weht", "blitzt"], "correctIndex": 1, "explanation": "Die Sonne scheint 阳光照耀。"},
        {"id": "A1_L12_Q10", "type": "EXAM_REAL", "question": "天气预报听力抓取：'Am Nachmittag kann es zu kurzen Gewittern kommen.' 意思是：", "options": ["下午会有短时雷阵雨", "下午全面降雪", "下午万里无云", "下午气温骤降到零下"], "correctIndex": 0, "explanation": "das Gewitter 指雷雨/雷阵雨。"}
    ],
    "A1_L13": [
        {"id": "A1_L13_Q1", "type": "GRAMMAR_FILL", "question": "完成时助动词选择（位置移动动词 gehen）：'Gestern _____ ich ins Kino gegangen.'", "options": ["habe", "bin", "hat", "ist"], "correctIndex": 1, "explanation": "表达空间位置移动的不及物动词（如 gehen, fahren, fliegen）完成时助动词必须用 sein！第一人称单数为 bin。"},
        {"id": "A1_L13_Q2", "type": "GRAMMAR_FILL", "question": "完成时助动词选择（及物动词 kaufen）：'Er _____ ein neues Handy gekauft.'", "options": ["ist", "hat", "wird", "war"], "correctIndex": 1, "explanation": "绝大多数及物动词（带四格宾语）完成时助动词统一用 haben！"},
        {"id": "A1_L13_Q3", "type": "GRAMMAR_FILL", "question": "规则动词 machen 的第二分词 (Partizip II) 是：", "options": ["gemacht", "gemachen", "gemachten", "macht"], "correctIndex": 0, "explanation": "规则动词第二分词公式：ge- + 词干 + -t，故为 gemacht。"},
        {"id": "A1_L13_Q4", "type": "GRAMMAR_FILL", "question": "可分动词 einkaufen 的第二分词构成法则（ge- 夹在中间）：", "options": ["geeinkauft", "eingekauft", "einkauft", "gekauft ein"], "correctIndex": 1, "explanation": "可分动词的 ge- 必须插在可分前缀与动词词干之间：ein-ge-kauft！"},
        {"id": "A1_L13_Q5", "type": "GRAMMAR_FILL", "question": "以 -ieren 结尾的外来动词第二分词【绝不加 ge-】：'Ich habe in Berlin _____.' (studieren)", "options": ["gestudiert", "studiert", "gestudieren", "studierte"], "correctIndex": 1, "explanation": "以 -ieren 结尾的动词绝不加前缀 ge-！直接以 -t 结尾：studiert, telefoniert, repariert。"},
        {"id": "A1_L13_Q6", "type": "GRAMMAR_FILL", "question": "动词 bleiben (停留) 的完成时助动词必须是 sein：'Am Sonntag _____ wir zu Hause geblieben.'", "options": ["haben", "sind", "hatten", "waren"], "correctIndex": 1, "explanation": "bleiben 与 sein 自身均强制选用 sein 作完成时助动词：wir sind geblieben。"},
        {"id": "A1_L13_Q7", "type": "SENTENCE_BUILDER", "question": "现在完成时句法框形结构：第二分词必须放置在句子的什么位置？", "options": ["紧跟在助动词后面", "句子最末尾", "句首第一位", "任意位置"], "correctIndex": 1, "explanation": "完成时框形结构铁律：助动词 haben/sein 占第 2 位，第二分词 (Partizip II) 必须永远沉底甩至句末！"},
        {"id": "A1_L13_Q8", "type": "VOCAB_MEANING", "question": "节日祝贺：'Herzlichen Glückwunsch zum Geburtstag!' 意思是：", "options": ["圣诞快乐！", "衷心祝你生日快乐！", "新年好！", "旅途顺风！"], "correctIndex": 1, "explanation": "zum Geburtstag gratulieren 祝贺生日；圣诞节是 Frohe Weihnachten！"},
        {"id": "A1_L13_Q9", "type": "GRAMMAR_FILL", "question": "不规则动词 essen 的第二分词是：'Wir haben Pizza _____.'", "options": ["geesst", "gegessen", "geessen", "gegesset"], "correctIndex": 1, "explanation": "essen 的第二分词为不规则形式 gegessen。"},
        {"id": "A1_L13_Q10", "type": "EXAM_REAL", "question": "写请假邮件或叙述经历：'Gestern habe ich den Zug verpasst.' 句中 verpassen 为不可分前缀动词，其分词特点是：", "options": ["加 ge- 变为 geverpasst", "不可分前缀 (ver-) 绝不加 ge-，直接为 verpasst", "加 -en 变为 verpassen", "不变位"], "correctIndex": 1, "explanation": "以 be-, ge-, er-, ver-, zer- 开头的不可分前缀动词，第二分词一律不加 ge-！故为 verpasst, bezahlt。"}
    ],
    "A1_L14": [
        {"id": "A1_L14_Q1", "type": "PRONUNCIATION", "question": "德语数字 21-99 的核心读法铁律是：", "options": ["先读十位再读个位", "个位在前，十位在后，中间用 und 连接 (如 21 = einundzwanzig)", "只读单个数字", "从大到小倒序读"], "correctIndex": 1, "explanation": "德语数字 21-99 颠倒顺序：个位数 + und + 十位数，如 25 = fünfundzwanzig。"},
        {"id": "A1_L14_Q2", "type": "PRONUNCIATION", "question": "数字 54 的德语拼读是：", "options": ["fünfzigvier", "vierundfünfzig", "fünfundvierzig", "vierzigfünf"], "correctIndex": 1, "explanation": "54 = 4 (vier) + und + 50 (fünfzig) -> vierundfünfzig。"},
        {"id": "A1_L14_Q3", "type": "GRAMMAR_FILL", "question": "时间钟点口语表达（致命易错！）：'halb drei' 指的是几点几分？", "options": ["3:30", "2:30", "3:15", "2:15"], "correctIndex": 1, "explanation": "halb 是指“差半小时到达该点钟”，halb drei 是已经走了一半去向三点，即 2:30（绝不是 3:30）！"},
        {"id": "A1_L14_Q4", "type": "GRAMMAR_FILL", "question": "时间钟点表达：'Viertel nach acht' 是指：", "options": ["8:15", "8:45", "7:45", "8:30"], "correctIndex": 0, "explanation": "Viertel nach acht = 8点过一刻（8点15分）；Viertel vor acht = 8点差一刻（7点45分）。"},
        {"id": "A1_L14_Q5", "type": "GRAMMAR_FILL", "question": "具体日期介词 am 后的序数词词尾：'Ich bin _____ dritten Mai geboren.'", "options": ["am", "im", "um", "an"], "correctIndex": 0, "explanation": "在某月某日使用介词 am (an dem)，序数词变为第三格加 -en：am dritten Mai。"},
        {"id": "A1_L14_Q6", "type": "PRONUNCIATION", "question": "序数词第一 'der erste' 与第三 'der dritte' 的特点是：", "options": ["完全规则变化", "属于特殊不规则序数词", "不加词尾", "只有复数"], "correctIndex": 1, "explanation": "1. der erste (不是 *einte), 3. der dritte (不是 *dreite), 7. der siebte (脱落 -en)。"},
        {"id": "A1_L14_Q7", "type": "VOCAB_MEANING", "question": "价格表达：'19,99 €' 的标准德语读法是：", "options": ["neunzehn Euro neunundneunzig", "neunzehn Cent neunundneunzig", "neunundneunzig Euro neunzehn", "zwanzig Euro"], "correctIndex": 0, "explanation": "欧元读法：整数 + Euro + 小数 (Cent)，如 neunzehn Euro neunundneunzig (Cent)。"},
        {"id": "A1_L14_Q8", "type": "GRAMMAR_FILL", "question": "20 及以上的序数词词尾规则（如第 20）：'der _____' (zwanzig)", "options": ["zwanzigte", "zwanzigste", "zwanzigten", "zwanzigest"], "correctIndex": 1, "explanation": "1-19 序数词加 -te；20 及以上加 -ste，故为 der zwanzigste。"},
        {"id": "A1_L14_Q9", "type": "LISTENING_MCQ", "question": "电话号码听写练习：'Null-eins-sieben-zwei' 对应的数字串是：", "options": ["0172", "0162", "0182", "0192"], "correctIndex": 0, "explanation": "null (0), eins (1), sieben (7), zwei (2) -> 0172。"},
        {"id": "A1_L14_Q10", "type": "EXAM_REAL", "question": "日历书写 '15.10.2026' 中数字后面的实心圆点代表：", "options": ["乘号", "序数词缩写标记 (der 15. = der fünfzehnte)", "句号", "无意义符号"], "correctIndex": 1, "explanation": "在德语中，阿拉伯数字后加圆点（如 1. / 15.）严格表示该数字为序数词！"}
    ],
    "A1_L15": [
        {"id": "A1_L15_Q1", "type": "EXAM_REAL", "question": "歌德 A1 写作给女性朋友（熟人）写便条，开头的称呼是：", "options": ["Lieber Anna,", "Liebe Anna,", "Sehr geehrte Anna,", "Hallo Herr Anna,"], "correctIndex": 1, "explanation": "熟人女性朋友信件称呼用 Liebe + 女性名字（后接逗号）；男性朋友用 Lieber + 男性名字。"},
        {"id": "A1_L15_Q2", "type": "EXAM_REAL", "question": "信件称呼后有逗号（如 Liebe Anna,），正文第一句首字母的规则是：", "options": ["必须大写", "必须小写（除非是名词或专有名词）", "随意大小写", "必须空两格"], "correctIndex": 1, "explanation": "德语书信称呼后打逗号，正文首句直接承接逗号，因此首字母【必须小写】！如：Liebe Anna, wie geht es dir?"},
        {"id": "A1_L15_Q3", "type": "EXAM_REAL", "question": "信件末尾的祝福语与署名标点规则（如 Viele Grüße）：", "options": ["后面必须打逗号", "后面必须打感叹号", "后面【绝不能打任何标点符号】", "必须加句号"], "correctIndex": 2, "explanation": "德语书信结尾祝福语（Viele Grüße / Mit freundlichen Grüßen）后面不加任何标点符号！直接另起一行签名。"},
        {"id": "A1_L15_Q4", "type": "LISTENING_MCQ", "question": "歌德 A1 口试 Teil 1 拼写自己的名字：考官说 'Buchstabieren Sie bitte Ihren Namen!' 考生应该：", "options": ["大声说出全名", "按德文字母表逐个念出自己名字的拼写字母", "写在纸上", "报手机号码"], "correctIndex": 1, "explanation": "buchstabieren 考查考生是否能熟练用德语字母发音拼出自己的姓氏或名字。"},
        {"id": "A1_L15_Q5", "type": "EXAM_REAL", "question": "歌德 A1 口试 Teil 2 抽到卡片【Thema: Sport / Wort: Wochenende】，最好的提问是：", "options": ["Wie heißt du?", "Treibst du am Wochenende Sport?", "Wo wohnst du?", "Was ist Sport?"], "correctIndex": 1, "explanation": "Teil 2 考查根据给定主题与单词构建符合交际语境的疑问句。"},
        {"id": "A1_L15_Q6", "type": "EXAM_REAL", "question": "歌德 A1 口试 Teil 3 抽到图片【禁烟标志】，最好的请求/指示表达是：", "options": ["Rauchen Sie bitte hier!", "Hier darf man nicht rauchen. Bitte machen Sie die Zigarette aus!", "Ich rauche gern.", "Wo ist die Zigarette?"], "correctIndex": 1, "explanation": "Teil 3 考查发出祈使请求与应对，禁烟标志需结合 verboten 或 Imperativ 要求灭烟。"},
        {"id": "A1_L15_Q7", "type": "GRAMMAR_FILL", "question": "A1 写作便条必写三要点之一（交代不能赴约的原因）：", "options": ["Ich kann leider nicht kommen, weil ich krank bin.", "Ich will kommen.", "Ich mag Party.", "Kommen Sie bitte!"], "correctIndex": 0, "explanation": "表达无法赴约并给出原因，使用 weil 从句或情态动词是最稳健的得分金句。"},
        {"id": "A1_L15_Q8", "type": "VOCAB_MEANING", "question": "考试告示理解：'Geöffnet: Mo-Fr 8:00 - 18:00'，周六能去办理业务吗？", "options": ["可以", "不可以，周六不营业", "只有周六上午开门", "不确定"], "correctIndex": 1, "explanation": "Mo-Fr 是 Montag bis Freitag（周一至周五）的官方缩写，周六（Samstag）不在营业时间内。"},
        {"id": "A1_L15_Q9", "type": "LISTENING_MCQ", "question": "广播通知抓取：'Der Zug nach München fällt heute aus.' 这列火车的状态是：", "options": ["晚点10分钟", "停运/取消开行", "已准时到达", "正在换乘"], "correctIndex": 1, "explanation": "ausfallen 意为“取消、停开、因故不上”。在德铁广播中是极高频考点词汇。"},
        {"id": "A1_L15_Q10", "type": "EXAM_REAL", "question": "歌德 A1 笔试总及格线要求是：", "options": ["100分满分中取得至少60分 (60%)", "必须每项都满分", "只需考口语", "50分即可"], "correctIndex": 0, "explanation": "歌德 A1 (Start Deutsch 1) 总分 100 分，满 60 分即为合格并获得终身有效的歌德证书。"}
    ]
}
